// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dense_gemv_dense_gemv,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a12t-cpg238-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.207000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=64,HLS_SYN_DSP=0,HLS_SYN_FF=10698,HLS_SYN_LUT=5265,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module dense_gemv (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 13;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [7:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] weights_0_q0;
wire   [31:0] weights_1_q0;
wire   [31:0] weights_2_q0;
wire   [31:0] weights_3_q0;
wire   [31:0] weights_4_q0;
wire   [31:0] weights_5_q0;
wire   [31:0] weights_6_q0;
wire   [31:0] weights_7_q0;
wire   [31:0] weights_8_q0;
wire   [31:0] weights_9_q0;
wire   [31:0] weights_10_q0;
wire   [31:0] weights_11_q0;
wire   [31:0] weights_12_q0;
wire   [31:0] weights_13_q0;
wire   [31:0] weights_14_q0;
wire   [31:0] weights_15_q0;
wire   [31:0] weights_16_q0;
wire   [31:0] weights_17_q0;
wire   [31:0] weights_18_q0;
wire   [31:0] weights_19_q0;
wire   [31:0] weights_20_q0;
wire   [31:0] weights_21_q0;
wire   [31:0] weights_22_q0;
wire   [31:0] weights_23_q0;
wire   [31:0] weights_24_q0;
wire   [31:0] weights_25_q0;
wire   [31:0] weights_26_q0;
wire   [31:0] weights_27_q0;
wire   [31:0] weights_28_q0;
wire   [31:0] weights_29_q0;
wire   [31:0] weights_30_q0;
wire   [31:0] weights_31_q0;
wire   [31:0] num_rows;
reg   [31:0] num_rows_read_reg_776;
wire    ap_CS_fsm_state4;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_done;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_idle;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_ready;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_in_stream_TREADY;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out1;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out1_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out2;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out2_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out3;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out3_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out4;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out4_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out5;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out5_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out6;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out6_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out7;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out7_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out8;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out8_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out9;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out9_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out10;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out10_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out11;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out11_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out12;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out12_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out13;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out13_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out14;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out14_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out15;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out15_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out16;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out16_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out17;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out17_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out18;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out18_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out19;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out19_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out20;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out20_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out21;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out21_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out22;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out22_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out23;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out23_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out24;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out24_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out25;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out25_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out26;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out26_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out27;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out27_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out28;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out28_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out29;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out29_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out30;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out30_ap_vld;
wire   [7:0] grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out31;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out31_ap_vld;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_done;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_idle;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_ready;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TREADY;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_ce0;
wire   [4:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_address0;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_ce0;
wire   [31:0] grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TDATA;
wire    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TVALID;
reg    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [31:0] out_stream_TDATA_reg;
wire    ap_CS_fsm_state6;
wire    regslice_both_out_stream_U_apdone_blk;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    regslice_both_in_stream_U_apdone_blk;
wire   [7:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_U_ack_in;
reg   [31:0] out_stream_TDATA_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg = 1'b0;
#0 grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg = 1'b0;
end

dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_25_1 grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start),
    .ap_done(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_done),
    .ap_idle(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_idle),
    .ap_ready(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_in_stream_TREADY),
    .p_out(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out),
    .p_out_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out_ap_vld),
    .p_out1(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out1),
    .p_out1_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out1_ap_vld),
    .p_out2(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out2),
    .p_out2_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out2_ap_vld),
    .p_out3(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out3),
    .p_out3_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out3_ap_vld),
    .p_out4(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out4),
    .p_out4_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out4_ap_vld),
    .p_out5(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out5),
    .p_out5_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out5_ap_vld),
    .p_out6(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out6),
    .p_out6_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out6_ap_vld),
    .p_out7(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out7),
    .p_out7_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out7_ap_vld),
    .p_out8(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out8),
    .p_out8_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out8_ap_vld),
    .p_out9(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out9),
    .p_out9_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out9_ap_vld),
    .p_out10(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out10),
    .p_out10_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out10_ap_vld),
    .p_out11(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out11),
    .p_out11_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out11_ap_vld),
    .p_out12(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out12),
    .p_out12_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out12_ap_vld),
    .p_out13(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out13),
    .p_out13_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out13_ap_vld),
    .p_out14(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out14),
    .p_out14_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out14_ap_vld),
    .p_out15(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out15),
    .p_out15_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out15_ap_vld),
    .p_out16(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out16),
    .p_out16_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out16_ap_vld),
    .p_out17(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out17),
    .p_out17_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out17_ap_vld),
    .p_out18(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out18),
    .p_out18_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out18_ap_vld),
    .p_out19(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out19),
    .p_out19_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out19_ap_vld),
    .p_out20(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out20),
    .p_out20_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out20_ap_vld),
    .p_out21(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out21),
    .p_out21_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out21_ap_vld),
    .p_out22(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out22),
    .p_out22_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out22_ap_vld),
    .p_out23(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out23),
    .p_out23_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out23_ap_vld),
    .p_out24(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out24),
    .p_out24_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out24_ap_vld),
    .p_out25(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out25),
    .p_out25_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out25_ap_vld),
    .p_out26(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out26),
    .p_out26_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out26_ap_vld),
    .p_out27(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out27),
    .p_out27_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out27_ap_vld),
    .p_out28(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out28),
    .p_out28_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out28_ap_vld),
    .p_out29(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out29),
    .p_out29_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out29_ap_vld),
    .p_out30(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out30),
    .p_out30_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out30_ap_vld),
    .p_out31(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out31),
    .p_out31_ap_vld(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out31_ap_vld)
);

dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_30_2 grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start),
    .ap_done(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_done),
    .ap_idle(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_idle),
    .ap_ready(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_ready),
    .out_stream_TREADY(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TREADY),
    .num_rows(num_rows_read_reg_776),
    .weights_0_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_address0),
    .weights_0_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_ce0),
    .weights_0_q0(weights_0_q0),
    .weights_1_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_address0),
    .weights_1_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_ce0),
    .weights_1_q0(weights_1_q0),
    .weights_2_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_address0),
    .weights_2_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_ce0),
    .weights_2_q0(weights_2_q0),
    .weights_3_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_address0),
    .weights_3_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_ce0),
    .weights_3_q0(weights_3_q0),
    .weights_4_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_address0),
    .weights_4_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_ce0),
    .weights_4_q0(weights_4_q0),
    .weights_5_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_address0),
    .weights_5_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_ce0),
    .weights_5_q0(weights_5_q0),
    .weights_6_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_address0),
    .weights_6_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_ce0),
    .weights_6_q0(weights_6_q0),
    .weights_7_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_address0),
    .weights_7_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_ce0),
    .weights_7_q0(weights_7_q0),
    .weights_8_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_address0),
    .weights_8_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_ce0),
    .weights_8_q0(weights_8_q0),
    .weights_9_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_address0),
    .weights_9_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_ce0),
    .weights_9_q0(weights_9_q0),
    .weights_10_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_address0),
    .weights_10_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_ce0),
    .weights_10_q0(weights_10_q0),
    .weights_11_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_address0),
    .weights_11_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_ce0),
    .weights_11_q0(weights_11_q0),
    .weights_12_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_address0),
    .weights_12_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_ce0),
    .weights_12_q0(weights_12_q0),
    .weights_13_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_address0),
    .weights_13_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_ce0),
    .weights_13_q0(weights_13_q0),
    .weights_14_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_address0),
    .weights_14_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_ce0),
    .weights_14_q0(weights_14_q0),
    .weights_15_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_address0),
    .weights_15_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_ce0),
    .weights_15_q0(weights_15_q0),
    .weights_16_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_address0),
    .weights_16_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_ce0),
    .weights_16_q0(weights_16_q0),
    .weights_17_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_address0),
    .weights_17_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_ce0),
    .weights_17_q0(weights_17_q0),
    .weights_18_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_address0),
    .weights_18_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_ce0),
    .weights_18_q0(weights_18_q0),
    .weights_19_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_address0),
    .weights_19_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_ce0),
    .weights_19_q0(weights_19_q0),
    .weights_20_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_address0),
    .weights_20_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_ce0),
    .weights_20_q0(weights_20_q0),
    .weights_21_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_address0),
    .weights_21_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_ce0),
    .weights_21_q0(weights_21_q0),
    .weights_22_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_address0),
    .weights_22_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_ce0),
    .weights_22_q0(weights_22_q0),
    .weights_23_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_address0),
    .weights_23_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_ce0),
    .weights_23_q0(weights_23_q0),
    .weights_24_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_address0),
    .weights_24_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_ce0),
    .weights_24_q0(weights_24_q0),
    .weights_25_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_address0),
    .weights_25_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_ce0),
    .weights_25_q0(weights_25_q0),
    .weights_26_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_address0),
    .weights_26_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_ce0),
    .weights_26_q0(weights_26_q0),
    .weights_27_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_address0),
    .weights_27_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_ce0),
    .weights_27_q0(weights_27_q0),
    .weights_28_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_address0),
    .weights_28_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_ce0),
    .weights_28_q0(weights_28_q0),
    .weights_29_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_address0),
    .weights_29_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_ce0),
    .weights_29_q0(weights_29_q0),
    .weights_30_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_address0),
    .weights_30_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_ce0),
    .weights_30_q0(weights_30_q0),
    .weights_31_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_address0),
    .weights_31_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_ce0),
    .weights_31_q0(weights_31_q0),
    .sext_ln36_31(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out),
    .sext_ln36_30(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out1),
    .sext_ln36_29(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out2),
    .sext_ln36_28(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out3),
    .sext_ln36_27(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out4),
    .sext_ln36_26(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out5),
    .sext_ln36_25(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out6),
    .sext_ln36_24(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out7),
    .sext_ln36_23(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out8),
    .sext_ln36_22(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out9),
    .sext_ln36_21(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out10),
    .sext_ln36_20(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out11),
    .sext_ln36_19(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out12),
    .sext_ln36_18(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out13),
    .sext_ln36_17(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out14),
    .sext_ln36_16(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out15),
    .sext_ln36_15(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out16),
    .sext_ln36_14(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out17),
    .sext_ln36_13(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out18),
    .sext_ln36_12(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out19),
    .sext_ln36_11(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out20),
    .sext_ln36_10(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out21),
    .sext_ln36_9(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out22),
    .sext_ln36_8(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out23),
    .sext_ln36_7(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out24),
    .sext_ln36_6(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out25),
    .sext_ln36_5(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out26),
    .sext_ln36_4(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out27),
    .sext_ln36_3(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out28),
    .sext_ln36_2(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out29),
    .sext_ln36(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out31),
    .sext_ln36_1(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out30),
    .out_stream_TDATA(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TDATA),
    .out_stream_TVALID(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TVALID)
);

dense_gemv_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .num_rows(num_rows),
    .weights_0_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_address0),
    .weights_0_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_ce0),
    .weights_0_q0(weights_0_q0),
    .weights_1_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_address0),
    .weights_1_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_ce0),
    .weights_1_q0(weights_1_q0),
    .weights_2_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_address0),
    .weights_2_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_ce0),
    .weights_2_q0(weights_2_q0),
    .weights_3_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_address0),
    .weights_3_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_ce0),
    .weights_3_q0(weights_3_q0),
    .weights_4_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_address0),
    .weights_4_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_ce0),
    .weights_4_q0(weights_4_q0),
    .weights_5_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_address0),
    .weights_5_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_ce0),
    .weights_5_q0(weights_5_q0),
    .weights_6_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_address0),
    .weights_6_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_ce0),
    .weights_6_q0(weights_6_q0),
    .weights_7_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_address0),
    .weights_7_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_ce0),
    .weights_7_q0(weights_7_q0),
    .weights_8_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_address0),
    .weights_8_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_ce0),
    .weights_8_q0(weights_8_q0),
    .weights_9_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_address0),
    .weights_9_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_ce0),
    .weights_9_q0(weights_9_q0),
    .weights_10_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_address0),
    .weights_10_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_ce0),
    .weights_10_q0(weights_10_q0),
    .weights_11_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_address0),
    .weights_11_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_ce0),
    .weights_11_q0(weights_11_q0),
    .weights_12_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_address0),
    .weights_12_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_ce0),
    .weights_12_q0(weights_12_q0),
    .weights_13_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_address0),
    .weights_13_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_ce0),
    .weights_13_q0(weights_13_q0),
    .weights_14_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_address0),
    .weights_14_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_ce0),
    .weights_14_q0(weights_14_q0),
    .weights_15_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_address0),
    .weights_15_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_ce0),
    .weights_15_q0(weights_15_q0),
    .weights_16_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_address0),
    .weights_16_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_ce0),
    .weights_16_q0(weights_16_q0),
    .weights_17_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_address0),
    .weights_17_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_ce0),
    .weights_17_q0(weights_17_q0),
    .weights_18_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_address0),
    .weights_18_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_ce0),
    .weights_18_q0(weights_18_q0),
    .weights_19_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_address0),
    .weights_19_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_ce0),
    .weights_19_q0(weights_19_q0),
    .weights_20_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_address0),
    .weights_20_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_ce0),
    .weights_20_q0(weights_20_q0),
    .weights_21_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_address0),
    .weights_21_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_ce0),
    .weights_21_q0(weights_21_q0),
    .weights_22_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_address0),
    .weights_22_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_ce0),
    .weights_22_q0(weights_22_q0),
    .weights_23_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_address0),
    .weights_23_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_ce0),
    .weights_23_q0(weights_23_q0),
    .weights_24_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_address0),
    .weights_24_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_ce0),
    .weights_24_q0(weights_24_q0),
    .weights_25_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_address0),
    .weights_25_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_ce0),
    .weights_25_q0(weights_25_q0),
    .weights_26_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_address0),
    .weights_26_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_ce0),
    .weights_26_q0(weights_26_q0),
    .weights_27_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_address0),
    .weights_27_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_ce0),
    .weights_27_q0(weights_27_q0),
    .weights_28_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_address0),
    .weights_28_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_ce0),
    .weights_28_q0(weights_28_q0),
    .weights_29_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_address0),
    .weights_29_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_ce0),
    .weights_29_q0(weights_29_q0),
    .weights_30_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_address0),
    .weights_30_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_ce0),
    .weights_30_q0(weights_30_q0),
    .weights_31_address0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_address0),
    .weights_31_ce0(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_ce0),
    .weights_31_q0(weights_31_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

dense_gemv_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_U_apdone_blk)
);

dense_gemv_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg <= 1'b1;
        end else if ((grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_ready == 1'b1)) begin
            grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg <= 1'b1;
        end else if ((grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_ready == 1'b1)) begin
            grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        num_rows_read_reg_776 <= num_rows;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        out_stream_TDATA_reg <= grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TDATA;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        out_stream_TDATA_int_regslice = grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TDATA;
    end else begin
        out_stream_TDATA_int_regslice = out_stream_TDATA_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((regslice_both_out_stream_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start = grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg;

assign grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start = grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg;

assign grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state5);

assign in_stream_TREADY = regslice_both_in_stream_U_ack_in;

assign out_stream_TVALID = regslice_both_out_stream_U_vld_out;

endmodule //dense_gemv
