// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_30_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_stream_TREADY,
        num_rows,
        weights_0_address0,
        weights_0_ce0,
        weights_0_q0,
        weights_1_address0,
        weights_1_ce0,
        weights_1_q0,
        weights_2_address0,
        weights_2_ce0,
        weights_2_q0,
        weights_3_address0,
        weights_3_ce0,
        weights_3_q0,
        weights_4_address0,
        weights_4_ce0,
        weights_4_q0,
        weights_5_address0,
        weights_5_ce0,
        weights_5_q0,
        weights_6_address0,
        weights_6_ce0,
        weights_6_q0,
        weights_7_address0,
        weights_7_ce0,
        weights_7_q0,
        weights_8_address0,
        weights_8_ce0,
        weights_8_q0,
        weights_9_address0,
        weights_9_ce0,
        weights_9_q0,
        weights_10_address0,
        weights_10_ce0,
        weights_10_q0,
        weights_11_address0,
        weights_11_ce0,
        weights_11_q0,
        weights_12_address0,
        weights_12_ce0,
        weights_12_q0,
        weights_13_address0,
        weights_13_ce0,
        weights_13_q0,
        weights_14_address0,
        weights_14_ce0,
        weights_14_q0,
        weights_15_address0,
        weights_15_ce0,
        weights_15_q0,
        weights_16_address0,
        weights_16_ce0,
        weights_16_q0,
        weights_17_address0,
        weights_17_ce0,
        weights_17_q0,
        weights_18_address0,
        weights_18_ce0,
        weights_18_q0,
        weights_19_address0,
        weights_19_ce0,
        weights_19_q0,
        weights_20_address0,
        weights_20_ce0,
        weights_20_q0,
        weights_21_address0,
        weights_21_ce0,
        weights_21_q0,
        weights_22_address0,
        weights_22_ce0,
        weights_22_q0,
        weights_23_address0,
        weights_23_ce0,
        weights_23_q0,
        weights_24_address0,
        weights_24_ce0,
        weights_24_q0,
        weights_25_address0,
        weights_25_ce0,
        weights_25_q0,
        weights_26_address0,
        weights_26_ce0,
        weights_26_q0,
        weights_27_address0,
        weights_27_ce0,
        weights_27_q0,
        weights_28_address0,
        weights_28_ce0,
        weights_28_q0,
        weights_29_address0,
        weights_29_ce0,
        weights_29_q0,
        weights_30_address0,
        weights_30_ce0,
        weights_30_q0,
        weights_31_address0,
        weights_31_ce0,
        weights_31_q0,
        sext_ln36_31,
        sext_ln36_30,
        sext_ln36_29,
        sext_ln36_28,
        sext_ln36_27,
        sext_ln36_26,
        sext_ln36_25,
        sext_ln36_24,
        sext_ln36_23,
        sext_ln36_22,
        sext_ln36_21,
        sext_ln36_20,
        sext_ln36_19,
        sext_ln36_18,
        sext_ln36_17,
        sext_ln36_16,
        sext_ln36_15,
        sext_ln36_14,
        sext_ln36_13,
        sext_ln36_12,
        sext_ln36_11,
        sext_ln36_10,
        sext_ln36_9,
        sext_ln36_8,
        sext_ln36_7,
        sext_ln36_6,
        sext_ln36_5,
        sext_ln36_4,
        sext_ln36_3,
        sext_ln36_2,
        sext_ln36,
        sext_ln36_1,
        out_stream_TDATA,
        out_stream_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   out_stream_TREADY;
input  [31:0] num_rows;
output  [4:0] weights_0_address0;
output   weights_0_ce0;
input  [31:0] weights_0_q0;
output  [4:0] weights_1_address0;
output   weights_1_ce0;
input  [31:0] weights_1_q0;
output  [4:0] weights_2_address0;
output   weights_2_ce0;
input  [31:0] weights_2_q0;
output  [4:0] weights_3_address0;
output   weights_3_ce0;
input  [31:0] weights_3_q0;
output  [4:0] weights_4_address0;
output   weights_4_ce0;
input  [31:0] weights_4_q0;
output  [4:0] weights_5_address0;
output   weights_5_ce0;
input  [31:0] weights_5_q0;
output  [4:0] weights_6_address0;
output   weights_6_ce0;
input  [31:0] weights_6_q0;
output  [4:0] weights_7_address0;
output   weights_7_ce0;
input  [31:0] weights_7_q0;
output  [4:0] weights_8_address0;
output   weights_8_ce0;
input  [31:0] weights_8_q0;
output  [4:0] weights_9_address0;
output   weights_9_ce0;
input  [31:0] weights_9_q0;
output  [4:0] weights_10_address0;
output   weights_10_ce0;
input  [31:0] weights_10_q0;
output  [4:0] weights_11_address0;
output   weights_11_ce0;
input  [31:0] weights_11_q0;
output  [4:0] weights_12_address0;
output   weights_12_ce0;
input  [31:0] weights_12_q0;
output  [4:0] weights_13_address0;
output   weights_13_ce0;
input  [31:0] weights_13_q0;
output  [4:0] weights_14_address0;
output   weights_14_ce0;
input  [31:0] weights_14_q0;
output  [4:0] weights_15_address0;
output   weights_15_ce0;
input  [31:0] weights_15_q0;
output  [4:0] weights_16_address0;
output   weights_16_ce0;
input  [31:0] weights_16_q0;
output  [4:0] weights_17_address0;
output   weights_17_ce0;
input  [31:0] weights_17_q0;
output  [4:0] weights_18_address0;
output   weights_18_ce0;
input  [31:0] weights_18_q0;
output  [4:0] weights_19_address0;
output   weights_19_ce0;
input  [31:0] weights_19_q0;
output  [4:0] weights_20_address0;
output   weights_20_ce0;
input  [31:0] weights_20_q0;
output  [4:0] weights_21_address0;
output   weights_21_ce0;
input  [31:0] weights_21_q0;
output  [4:0] weights_22_address0;
output   weights_22_ce0;
input  [31:0] weights_22_q0;
output  [4:0] weights_23_address0;
output   weights_23_ce0;
input  [31:0] weights_23_q0;
output  [4:0] weights_24_address0;
output   weights_24_ce0;
input  [31:0] weights_24_q0;
output  [4:0] weights_25_address0;
output   weights_25_ce0;
input  [31:0] weights_25_q0;
output  [4:0] weights_26_address0;
output   weights_26_ce0;
input  [31:0] weights_26_q0;
output  [4:0] weights_27_address0;
output   weights_27_ce0;
input  [31:0] weights_27_q0;
output  [4:0] weights_28_address0;
output   weights_28_ce0;
input  [31:0] weights_28_q0;
output  [4:0] weights_29_address0;
output   weights_29_ce0;
input  [31:0] weights_29_q0;
output  [4:0] weights_30_address0;
output   weights_30_ce0;
input  [31:0] weights_30_q0;
output  [4:0] weights_31_address0;
output   weights_31_ce0;
input  [31:0] weights_31_q0;
input  [7:0] sext_ln36_31;
input  [7:0] sext_ln36_30;
input  [7:0] sext_ln36_29;
input  [7:0] sext_ln36_28;
input  [7:0] sext_ln36_27;
input  [7:0] sext_ln36_26;
input  [7:0] sext_ln36_25;
input  [7:0] sext_ln36_24;
input  [7:0] sext_ln36_23;
input  [7:0] sext_ln36_22;
input  [7:0] sext_ln36_21;
input  [7:0] sext_ln36_20;
input  [7:0] sext_ln36_19;
input  [7:0] sext_ln36_18;
input  [7:0] sext_ln36_17;
input  [7:0] sext_ln36_16;
input  [7:0] sext_ln36_15;
input  [7:0] sext_ln36_14;
input  [7:0] sext_ln36_13;
input  [7:0] sext_ln36_12;
input  [7:0] sext_ln36_11;
input  [7:0] sext_ln36_10;
input  [7:0] sext_ln36_9;
input  [7:0] sext_ln36_8;
input  [7:0] sext_ln36_7;
input  [7:0] sext_ln36_6;
input  [7:0] sext_ln36_5;
input  [7:0] sext_ln36_4;
input  [7:0] sext_ln36_3;
input  [7:0] sext_ln36_2;
input  [7:0] sext_ln36;
input  [7:0] sext_ln36_1;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;

reg ap_idle;
reg out_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln30_fu_1101_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    out_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire  signed [31:0] sext_ln36_1_cast_fu_961_p1;
reg  signed [31:0] sext_ln36_1_cast_reg_1279;
reg    ap_block_pp0_stage0_11001_grp1;
wire  signed [31:0] sext_ln36_cast_fu_965_p1;
reg  signed [31:0] sext_ln36_cast_reg_1284;
wire  signed [31:0] sext_ln36_2_cast_fu_969_p1;
reg  signed [31:0] sext_ln36_2_cast_reg_1289;
wire  signed [31:0] sext_ln36_3_cast_fu_973_p1;
reg  signed [31:0] sext_ln36_3_cast_reg_1294;
wire  signed [31:0] sext_ln36_4_cast_fu_977_p1;
reg  signed [31:0] sext_ln36_4_cast_reg_1299;
wire  signed [31:0] sext_ln36_5_cast_fu_981_p1;
reg  signed [31:0] sext_ln36_5_cast_reg_1304;
wire  signed [31:0] sext_ln36_6_cast_fu_985_p1;
reg  signed [31:0] sext_ln36_6_cast_reg_1309;
wire  signed [31:0] sext_ln36_7_cast_fu_989_p1;
reg  signed [31:0] sext_ln36_7_cast_reg_1314;
wire  signed [31:0] sext_ln36_8_cast_fu_993_p1;
reg  signed [31:0] sext_ln36_8_cast_reg_1319;
wire  signed [31:0] sext_ln36_9_cast_fu_997_p1;
reg  signed [31:0] sext_ln36_9_cast_reg_1324;
wire  signed [31:0] sext_ln36_10_cast_fu_1001_p1;
reg  signed [31:0] sext_ln36_10_cast_reg_1329;
wire  signed [31:0] sext_ln36_11_cast_fu_1005_p1;
reg  signed [31:0] sext_ln36_11_cast_reg_1334;
wire  signed [31:0] sext_ln36_12_cast_fu_1009_p1;
reg  signed [31:0] sext_ln36_12_cast_reg_1339;
wire  signed [31:0] sext_ln36_13_cast_fu_1013_p1;
reg  signed [31:0] sext_ln36_13_cast_reg_1344;
wire  signed [31:0] sext_ln36_14_cast_fu_1017_p1;
reg  signed [31:0] sext_ln36_14_cast_reg_1349;
wire  signed [31:0] sext_ln36_15_cast_fu_1021_p1;
reg  signed [31:0] sext_ln36_15_cast_reg_1354;
wire  signed [31:0] sext_ln36_16_cast_fu_1025_p1;
reg  signed [31:0] sext_ln36_16_cast_reg_1359;
wire  signed [31:0] sext_ln36_17_cast_fu_1029_p1;
reg  signed [31:0] sext_ln36_17_cast_reg_1364;
wire  signed [31:0] sext_ln36_18_cast_fu_1033_p1;
reg  signed [31:0] sext_ln36_18_cast_reg_1369;
wire  signed [31:0] sext_ln36_19_cast_fu_1037_p1;
reg  signed [31:0] sext_ln36_19_cast_reg_1374;
wire  signed [31:0] sext_ln36_20_cast_fu_1041_p1;
reg  signed [31:0] sext_ln36_20_cast_reg_1379;
wire  signed [31:0] sext_ln36_21_cast_fu_1045_p1;
reg  signed [31:0] sext_ln36_21_cast_reg_1384;
wire  signed [31:0] sext_ln36_22_cast_fu_1049_p1;
reg  signed [31:0] sext_ln36_22_cast_reg_1389;
wire  signed [31:0] sext_ln36_23_cast_fu_1053_p1;
reg  signed [31:0] sext_ln36_23_cast_reg_1394;
wire  signed [31:0] sext_ln36_24_cast_fu_1057_p1;
reg  signed [31:0] sext_ln36_24_cast_reg_1399;
wire  signed [31:0] sext_ln36_25_cast_fu_1061_p1;
reg  signed [31:0] sext_ln36_25_cast_reg_1404;
wire  signed [31:0] sext_ln36_26_cast_fu_1065_p1;
reg  signed [31:0] sext_ln36_26_cast_reg_1409;
wire  signed [31:0] sext_ln36_27_cast_fu_1069_p1;
reg  signed [31:0] sext_ln36_27_cast_reg_1414;
wire  signed [31:0] sext_ln36_28_cast_fu_1073_p1;
reg  signed [31:0] sext_ln36_28_cast_reg_1419;
reg    ap_block_pp0_stage0_11001;
wire  signed [31:0] sext_ln36_29_cast_fu_1077_p1;
reg  signed [31:0] sext_ln36_29_cast_reg_1424;
wire  signed [31:0] sext_ln36_30_cast_fu_1081_p1;
reg  signed [31:0] sext_ln36_30_cast_reg_1429;
wire  signed [31:0] sext_ln36_31_cast_fu_1085_p1;
reg  signed [31:0] sext_ln36_31_cast_reg_1434;
wire   [63:0] zext_ln30_fu_1113_p1;
reg   [63:0] zext_ln30_reg_1443;
reg   [63:0] zext_ln30_reg_1443_pp0_iter1_reg;
wire   [31:0] grp_fu_801_p2;
reg   [31:0] mul_ln36_reg_1755;
wire   [31:0] grp_fu_806_p2;
reg   [31:0] mul_ln36_1_reg_1760;
wire   [31:0] grp_fu_811_p2;
reg   [31:0] mul_ln36_2_reg_1765;
wire   [31:0] grp_fu_816_p2;
reg   [31:0] mul_ln36_3_reg_1770;
wire   [31:0] grp_fu_821_p2;
reg   [31:0] mul_ln36_4_reg_1815;
wire   [31:0] grp_fu_826_p2;
reg   [31:0] mul_ln36_5_reg_1820;
wire   [31:0] grp_fu_831_p2;
reg   [31:0] mul_ln36_6_reg_1825;
wire   [31:0] grp_fu_836_p2;
reg   [31:0] mul_ln36_7_reg_1830;
wire   [31:0] grp_fu_841_p2;
reg   [31:0] mul_ln36_8_reg_1835;
wire   [31:0] grp_fu_846_p2;
reg   [31:0] mul_ln36_9_reg_1840;
wire   [31:0] grp_fu_851_p2;
reg   [31:0] mul_ln36_10_reg_1845;
wire   [31:0] grp_fu_856_p2;
reg   [31:0] mul_ln36_11_reg_1850;
wire   [31:0] grp_fu_861_p2;
reg   [31:0] mul_ln36_12_reg_1855;
wire   [31:0] grp_fu_866_p2;
reg   [31:0] mul_ln36_13_reg_1860;
wire   [31:0] grp_fu_871_p2;
reg   [31:0] mul_ln36_14_reg_1865;
wire   [31:0] grp_fu_876_p2;
reg   [31:0] mul_ln36_15_reg_1870;
wire   [31:0] grp_fu_881_p2;
reg   [31:0] mul_ln36_16_reg_1875;
wire   [31:0] grp_fu_886_p2;
reg   [31:0] mul_ln36_17_reg_1880;
wire   [31:0] grp_fu_891_p2;
reg   [31:0] mul_ln36_18_reg_1885;
wire   [31:0] grp_fu_896_p2;
reg   [31:0] mul_ln36_19_reg_1890;
wire   [31:0] grp_fu_901_p2;
reg   [31:0] mul_ln36_24_reg_1895;
wire   [31:0] grp_fu_906_p2;
reg   [31:0] mul_ln36_25_reg_1900;
wire   [31:0] grp_fu_911_p2;
reg   [31:0] mul_ln36_26_reg_1905;
wire   [31:0] grp_fu_916_p2;
reg   [31:0] mul_ln36_27_reg_1910;
wire   [31:0] add_ln36_27_fu_1134_p2;
reg   [31:0] add_ln36_27_reg_1915;
wire   [31:0] grp_fu_921_p2;
reg   [31:0] mul_ln36_20_reg_1920;
wire   [31:0] grp_fu_926_p2;
reg   [31:0] mul_ln36_21_reg_1925;
wire   [31:0] grp_fu_931_p2;
reg   [31:0] mul_ln36_22_reg_1930;
wire   [31:0] grp_fu_936_p2;
reg   [31:0] mul_ln36_23_reg_1935;
wire   [31:0] grp_fu_941_p2;
reg   [31:0] mul_ln36_28_reg_1940;
wire   [31:0] grp_fu_946_p2;
reg   [31:0] mul_ln36_29_reg_1945;
wire   [31:0] grp_fu_951_p2;
reg   [31:0] mul_ln36_30_reg_1950;
wire   [31:0] grp_fu_956_p2;
reg   [31:0] mul_ln36_31_reg_1955;
wire   [31:0] add_ln36_5_fu_1148_p2;
reg   [31:0] add_ln36_5_reg_1960;
wire   [31:0] add_ln36_12_fu_1162_p2;
reg   [31:0] add_ln36_12_reg_1965;
wire   [31:0] add_ln36_17_fu_1176_p2;
reg   [31:0] add_ln36_17_reg_1970;
wire   [31:0] add_ln36_20_fu_1190_p2;
reg   [31:0] add_ln36_20_reg_1975;
wire   [31:0] add_ln36_28_fu_1210_p2;
reg   [31:0] add_ln36_28_reg_1980;
wire   [31:0] add_ln36_6_fu_1229_p2;
reg   [31:0] add_ln36_6_reg_1985;
wire   [31:0] add_ln36_13_fu_1248_p2;
reg   [31:0] add_ln36_13_reg_1990;
wire   [31:0] add_ln36_29_fu_1257_p2;
reg   [31:0] add_ln36_29_reg_1995;
wire    ap_block_pp0_stage0;
reg   [30:0] i_fu_176;
wire   [30:0] add_ln30_fu_1107_p2;
wire    ap_loop_init;
reg   [30:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001_grp1;
reg    weights_28_ce0_local;
reg    weights_29_ce0_local;
reg    weights_30_ce0_local;
reg    weights_31_ce0_local;
reg    weights_4_ce0_local;
reg    weights_5_ce0_local;
reg    weights_6_ce0_local;
reg    weights_7_ce0_local;
reg    weights_12_ce0_local;
reg    weights_13_ce0_local;
reg    weights_14_ce0_local;
reg    weights_15_ce0_local;
reg    weights_16_ce0_local;
reg    weights_17_ce0_local;
reg    weights_18_ce0_local;
reg    weights_19_ce0_local;
reg    weights_20_ce0_local;
reg    weights_21_ce0_local;
reg    weights_22_ce0_local;
reg    weights_23_ce0_local;
reg    weights_24_ce0_local;
reg    weights_25_ce0_local;
reg    weights_26_ce0_local;
reg    weights_27_ce0_local;
reg    weights_0_ce0_local;
reg    weights_1_ce0_local;
reg    weights_2_ce0_local;
reg    weights_3_ce0_local;
reg    weights_8_ce0_local;
reg    weights_9_ce0_local;
reg    weights_10_ce0_local;
reg    weights_11_ce0_local;
wire  signed [7:0] grp_fu_801_p1;
wire  signed [7:0] grp_fu_806_p1;
wire  signed [7:0] grp_fu_811_p1;
wire  signed [7:0] grp_fu_816_p1;
wire  signed [7:0] grp_fu_821_p1;
wire  signed [7:0] grp_fu_826_p1;
wire  signed [7:0] grp_fu_831_p1;
wire  signed [7:0] grp_fu_836_p1;
wire  signed [7:0] grp_fu_841_p1;
wire  signed [7:0] grp_fu_846_p1;
wire  signed [7:0] grp_fu_851_p1;
wire  signed [7:0] grp_fu_856_p1;
wire  signed [7:0] grp_fu_861_p1;
wire  signed [7:0] grp_fu_866_p1;
wire  signed [7:0] grp_fu_871_p1;
wire  signed [7:0] grp_fu_876_p1;
wire  signed [7:0] grp_fu_881_p1;
wire  signed [7:0] grp_fu_886_p1;
wire  signed [7:0] grp_fu_891_p1;
wire  signed [7:0] grp_fu_896_p1;
wire  signed [7:0] grp_fu_901_p1;
wire  signed [7:0] grp_fu_906_p1;
wire  signed [7:0] grp_fu_911_p1;
wire  signed [7:0] grp_fu_916_p1;
wire  signed [7:0] grp_fu_921_p1;
wire  signed [7:0] grp_fu_926_p1;
wire  signed [7:0] grp_fu_931_p1;
wire  signed [7:0] grp_fu_936_p1;
wire  signed [7:0] grp_fu_941_p1;
wire  signed [7:0] grp_fu_946_p1;
wire  signed [7:0] grp_fu_951_p1;
wire  signed [7:0] grp_fu_956_p1;
wire   [31:0] zext_ln30_1_fu_1097_p1;
wire   [31:0] add_ln36_26_fu_1130_p2;
wire   [31:0] add_ln36_25_fu_1126_p2;
wire   [31:0] add_ln36_4_fu_1144_p2;
wire   [31:0] add_ln36_3_fu_1140_p2;
wire   [31:0] add_ln36_11_fu_1158_p2;
wire   [31:0] add_ln36_10_fu_1154_p2;
wire   [31:0] add_ln36_16_fu_1172_p2;
wire   [31:0] add_ln36_15_fu_1168_p2;
wire   [31:0] add_ln36_19_fu_1186_p2;
wire   [31:0] add_ln36_18_fu_1182_p2;
wire   [31:0] add_ln36_23_fu_1200_p2;
wire   [31:0] add_ln36_22_fu_1196_p2;
wire   [31:0] add_ln36_24_fu_1204_p2;
wire   [31:0] add_ln36_1_fu_1219_p2;
wire   [31:0] add_ln36_fu_1215_p2;
wire   [31:0] add_ln36_2_fu_1223_p2;
wire   [31:0] add_ln36_8_fu_1238_p2;
wire   [31:0] add_ln36_7_fu_1234_p2;
wire   [31:0] add_ln36_9_fu_1242_p2;
wire   [31:0] add_ln36_21_fu_1253_p2;
wire   [31:0] add_ln36_14_fu_1262_p2;
reg    grp_fu_801_ce;
reg    grp_fu_806_ce;
reg    grp_fu_811_ce;
reg    grp_fu_816_ce;
reg    grp_fu_821_ce;
reg    grp_fu_826_ce;
reg    grp_fu_831_ce;
reg    grp_fu_836_ce;
reg    grp_fu_841_ce;
reg    grp_fu_846_ce;
reg    grp_fu_851_ce;
reg    grp_fu_856_ce;
reg    grp_fu_861_ce;
reg    grp_fu_866_ce;
reg    grp_fu_871_ce;
reg    grp_fu_876_ce;
reg    grp_fu_881_ce;
reg    grp_fu_886_ce;
reg    grp_fu_891_ce;
reg    grp_fu_896_ce;
reg    grp_fu_901_ce;
reg    grp_fu_906_ce;
reg    grp_fu_911_ce;
reg    grp_fu_916_ce;
reg    grp_fu_921_ce;
reg    grp_fu_926_ce;
reg    grp_fu_931_ce;
reg    grp_fu_936_ce;
reg    grp_fu_941_ce;
reg    grp_fu_946_ce;
reg    grp_fu_951_ce;
reg    grp_fu_956_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 i_fu_176 = 31'd0;
#0 ap_done_reg = 1'b0;
end

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_31_q0),
    .din1(grp_fu_801_p1),
    .ce(grp_fu_801_ce),
    .dout(grp_fu_801_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_30_q0),
    .din1(grp_fu_806_p1),
    .ce(grp_fu_806_ce),
    .dout(grp_fu_806_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_29_q0),
    .din1(grp_fu_811_p1),
    .ce(grp_fu_811_ce),
    .dout(grp_fu_811_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_28_q0),
    .din1(grp_fu_816_p1),
    .ce(grp_fu_816_ce),
    .dout(grp_fu_816_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_27_q0),
    .din1(grp_fu_821_p1),
    .ce(grp_fu_821_ce),
    .dout(grp_fu_821_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_26_q0),
    .din1(grp_fu_826_p1),
    .ce(grp_fu_826_ce),
    .dout(grp_fu_826_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_25_q0),
    .din1(grp_fu_831_p1),
    .ce(grp_fu_831_ce),
    .dout(grp_fu_831_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_24_q0),
    .din1(grp_fu_836_p1),
    .ce(grp_fu_836_ce),
    .dout(grp_fu_836_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_23_q0),
    .din1(grp_fu_841_p1),
    .ce(grp_fu_841_ce),
    .dout(grp_fu_841_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_22_q0),
    .din1(grp_fu_846_p1),
    .ce(grp_fu_846_ce),
    .dout(grp_fu_846_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_21_q0),
    .din1(grp_fu_851_p1),
    .ce(grp_fu_851_ce),
    .dout(grp_fu_851_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_20_q0),
    .din1(grp_fu_856_p1),
    .ce(grp_fu_856_ce),
    .dout(grp_fu_856_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_19_q0),
    .din1(grp_fu_861_p1),
    .ce(grp_fu_861_ce),
    .dout(grp_fu_861_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_18_q0),
    .din1(grp_fu_866_p1),
    .ce(grp_fu_866_ce),
    .dout(grp_fu_866_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_17_q0),
    .din1(grp_fu_871_p1),
    .ce(grp_fu_871_ce),
    .dout(grp_fu_871_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_16_q0),
    .din1(grp_fu_876_p1),
    .ce(grp_fu_876_ce),
    .dout(grp_fu_876_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_15_q0),
    .din1(grp_fu_881_p1),
    .ce(grp_fu_881_ce),
    .dout(grp_fu_881_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_14_q0),
    .din1(grp_fu_886_p1),
    .ce(grp_fu_886_ce),
    .dout(grp_fu_886_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_13_q0),
    .din1(grp_fu_891_p1),
    .ce(grp_fu_891_ce),
    .dout(grp_fu_891_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_12_q0),
    .din1(grp_fu_896_p1),
    .ce(grp_fu_896_ce),
    .dout(grp_fu_896_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_7_q0),
    .din1(grp_fu_901_p1),
    .ce(grp_fu_901_ce),
    .dout(grp_fu_901_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_6_q0),
    .din1(grp_fu_906_p1),
    .ce(grp_fu_906_ce),
    .dout(grp_fu_906_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_5_q0),
    .din1(grp_fu_911_p1),
    .ce(grp_fu_911_ce),
    .dout(grp_fu_911_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_4_q0),
    .din1(grp_fu_916_p1),
    .ce(grp_fu_916_ce),
    .dout(grp_fu_916_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_11_q0),
    .din1(grp_fu_921_p1),
    .ce(grp_fu_921_ce),
    .dout(grp_fu_921_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_10_q0),
    .din1(grp_fu_926_p1),
    .ce(grp_fu_926_ce),
    .dout(grp_fu_926_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_9_q0),
    .din1(grp_fu_931_p1),
    .ce(grp_fu_931_ce),
    .dout(grp_fu_931_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_8_q0),
    .din1(grp_fu_936_p1),
    .ce(grp_fu_936_ce),
    .dout(grp_fu_936_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_3_q0),
    .din1(grp_fu_941_p1),
    .ce(grp_fu_941_ce),
    .dout(grp_fu_941_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_2_q0),
    .din1(grp_fu_946_p1),
    .ce(grp_fu_946_ce),
    .dout(grp_fu_946_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_0_q0),
    .din1(grp_fu_951_p1),
    .ce(grp_fu_951_ce),
    .dout(grp_fu_951_p2)
);

dense_gemv_mul_32s_8s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_32s_8s_32_2_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(weights_1_q0),
    .din1(grp_fu_956_p1),
    .ce(grp_fu_956_ce),
    .dout(grp_fu_956_p2)
);

dense_gemv_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln30_fu_1101_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_176 <= add_ln30_fu_1107_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_176 <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        add_ln36_12_reg_1965 <= add_ln36_12_fu_1162_p2;
        add_ln36_13_reg_1990 <= add_ln36_13_fu_1248_p2;
        add_ln36_17_reg_1970 <= add_ln36_17_fu_1176_p2;
        add_ln36_20_reg_1975 <= add_ln36_20_fu_1190_p2;
        add_ln36_27_reg_1915 <= add_ln36_27_fu_1134_p2;
        add_ln36_28_reg_1980 <= add_ln36_28_fu_1210_p2;
        add_ln36_29_reg_1995 <= add_ln36_29_fu_1257_p2;
        add_ln36_5_reg_1960 <= add_ln36_5_fu_1148_p2;
        add_ln36_6_reg_1985 <= add_ln36_6_fu_1229_p2;
        mul_ln36_10_reg_1845 <= grp_fu_851_p2;
        mul_ln36_11_reg_1850 <= grp_fu_856_p2;
        mul_ln36_12_reg_1855 <= grp_fu_861_p2;
        mul_ln36_13_reg_1860 <= grp_fu_866_p2;
        mul_ln36_14_reg_1865 <= grp_fu_871_p2;
        mul_ln36_15_reg_1870 <= grp_fu_876_p2;
        mul_ln36_16_reg_1875 <= grp_fu_881_p2;
        mul_ln36_17_reg_1880 <= grp_fu_886_p2;
        mul_ln36_18_reg_1885 <= grp_fu_891_p2;
        mul_ln36_19_reg_1890 <= grp_fu_896_p2;
        mul_ln36_20_reg_1920 <= grp_fu_921_p2;
        mul_ln36_21_reg_1925 <= grp_fu_926_p2;
        mul_ln36_22_reg_1930 <= grp_fu_931_p2;
        mul_ln36_23_reg_1935 <= grp_fu_936_p2;
        mul_ln36_24_reg_1895 <= grp_fu_901_p2;
        mul_ln36_25_reg_1900 <= grp_fu_906_p2;
        mul_ln36_26_reg_1905 <= grp_fu_911_p2;
        mul_ln36_27_reg_1910 <= grp_fu_916_p2;
        mul_ln36_28_reg_1940 <= grp_fu_941_p2;
        mul_ln36_29_reg_1945 <= grp_fu_946_p2;
        mul_ln36_30_reg_1950 <= grp_fu_951_p2;
        mul_ln36_31_reg_1955 <= grp_fu_956_p2;
        mul_ln36_4_reg_1815 <= grp_fu_821_p2;
        mul_ln36_5_reg_1820 <= grp_fu_826_p2;
        mul_ln36_6_reg_1825 <= grp_fu_831_p2;
        mul_ln36_7_reg_1830 <= grp_fu_836_p2;
        mul_ln36_8_reg_1835 <= grp_fu_841_p2;
        mul_ln36_9_reg_1840 <= grp_fu_846_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        sext_ln36_28_cast_reg_1419 <= sext_ln36_28_cast_fu_1073_p1;
        sext_ln36_29_cast_reg_1424 <= sext_ln36_29_cast_fu_1077_p1;
        sext_ln36_30_cast_reg_1429 <= sext_ln36_30_cast_fu_1081_p1;
        sext_ln36_31_cast_reg_1434 <= sext_ln36_31_cast_fu_1085_p1;
        zext_ln30_reg_1443[30 : 0] <= zext_ln30_fu_1113_p1[30 : 0];
        zext_ln30_reg_1443_pp0_iter1_reg[30 : 0] <= zext_ln30_reg_1443[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        mul_ln36_1_reg_1760 <= grp_fu_806_p2;
        mul_ln36_2_reg_1765 <= grp_fu_811_p2;
        mul_ln36_3_reg_1770 <= grp_fu_816_p2;
        mul_ln36_reg_1755 <= grp_fu_801_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sext_ln36_10_cast_reg_1329 <= sext_ln36_10_cast_fu_1001_p1;
        sext_ln36_11_cast_reg_1334 <= sext_ln36_11_cast_fu_1005_p1;
        sext_ln36_12_cast_reg_1339 <= sext_ln36_12_cast_fu_1009_p1;
        sext_ln36_13_cast_reg_1344 <= sext_ln36_13_cast_fu_1013_p1;
        sext_ln36_14_cast_reg_1349 <= sext_ln36_14_cast_fu_1017_p1;
        sext_ln36_15_cast_reg_1354 <= sext_ln36_15_cast_fu_1021_p1;
        sext_ln36_16_cast_reg_1359 <= sext_ln36_16_cast_fu_1025_p1;
        sext_ln36_17_cast_reg_1364 <= sext_ln36_17_cast_fu_1029_p1;
        sext_ln36_18_cast_reg_1369 <= sext_ln36_18_cast_fu_1033_p1;
        sext_ln36_19_cast_reg_1374 <= sext_ln36_19_cast_fu_1037_p1;
        sext_ln36_1_cast_reg_1279 <= sext_ln36_1_cast_fu_961_p1;
        sext_ln36_20_cast_reg_1379 <= sext_ln36_20_cast_fu_1041_p1;
        sext_ln36_21_cast_reg_1384 <= sext_ln36_21_cast_fu_1045_p1;
        sext_ln36_22_cast_reg_1389 <= sext_ln36_22_cast_fu_1049_p1;
        sext_ln36_23_cast_reg_1394 <= sext_ln36_23_cast_fu_1053_p1;
        sext_ln36_24_cast_reg_1399 <= sext_ln36_24_cast_fu_1057_p1;
        sext_ln36_25_cast_reg_1404 <= sext_ln36_25_cast_fu_1061_p1;
        sext_ln36_26_cast_reg_1409 <= sext_ln36_26_cast_fu_1065_p1;
        sext_ln36_27_cast_reg_1414 <= sext_ln36_27_cast_fu_1069_p1;
        sext_ln36_2_cast_reg_1289 <= sext_ln36_2_cast_fu_969_p1;
        sext_ln36_3_cast_reg_1294 <= sext_ln36_3_cast_fu_973_p1;
        sext_ln36_4_cast_reg_1299 <= sext_ln36_4_cast_fu_977_p1;
        sext_ln36_5_cast_reg_1304 <= sext_ln36_5_cast_fu_981_p1;
        sext_ln36_6_cast_reg_1309 <= sext_ln36_6_cast_fu_985_p1;
        sext_ln36_7_cast_reg_1314 <= sext_ln36_7_cast_fu_989_p1;
        sext_ln36_8_cast_reg_1319 <= sext_ln36_8_cast_fu_993_p1;
        sext_ln36_9_cast_reg_1324 <= sext_ln36_9_cast_fu_997_p1;
        sext_ln36_cast_reg_1284 <= sext_ln36_cast_fu_965_p1;
    end
end

always @ (*) begin
    if (((icmp_ln30_fu_1101_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 31'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_176;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_801_ce = 1'b1;
    end else begin
        grp_fu_801_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_806_ce = 1'b1;
    end else begin
        grp_fu_806_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_811_ce = 1'b1;
    end else begin
        grp_fu_811_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_816_ce = 1'b1;
    end else begin
        grp_fu_816_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_821_ce = 1'b1;
    end else begin
        grp_fu_821_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_826_ce = 1'b1;
    end else begin
        grp_fu_826_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_831_ce = 1'b1;
    end else begin
        grp_fu_831_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_836_ce = 1'b1;
    end else begin
        grp_fu_836_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_841_ce = 1'b1;
    end else begin
        grp_fu_841_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_846_ce = 1'b1;
    end else begin
        grp_fu_846_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_851_ce = 1'b1;
    end else begin
        grp_fu_851_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_856_ce = 1'b1;
    end else begin
        grp_fu_856_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_861_ce = 1'b1;
    end else begin
        grp_fu_861_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_866_ce = 1'b1;
    end else begin
        grp_fu_866_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_871_ce = 1'b1;
    end else begin
        grp_fu_871_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_876_ce = 1'b1;
    end else begin
        grp_fu_876_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_881_ce = 1'b1;
    end else begin
        grp_fu_881_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_886_ce = 1'b1;
    end else begin
        grp_fu_886_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_891_ce = 1'b1;
    end else begin
        grp_fu_891_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_896_ce = 1'b1;
    end else begin
        grp_fu_896_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_901_ce = 1'b1;
    end else begin
        grp_fu_901_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_906_ce = 1'b1;
    end else begin
        grp_fu_906_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_911_ce = 1'b1;
    end else begin
        grp_fu_911_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_916_ce = 1'b1;
    end else begin
        grp_fu_916_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_921_ce = 1'b1;
    end else begin
        grp_fu_921_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_926_ce = 1'b1;
    end else begin
        grp_fu_926_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_931_ce = 1'b1;
    end else begin
        grp_fu_931_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_936_ce = 1'b1;
    end else begin
        grp_fu_936_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_941_ce = 1'b1;
    end else begin
        grp_fu_941_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_946_ce = 1'b1;
    end else begin
        grp_fu_946_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_951_ce = 1'b1;
    end else begin
        grp_fu_951_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_956_ce = 1'b1;
    end else begin
        grp_fu_956_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weights_0_ce0_local = 1'b1;
    end else begin
        weights_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weights_10_ce0_local = 1'b1;
    end else begin
        weights_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weights_11_ce0_local = 1'b1;
    end else begin
        weights_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_12_ce0_local = 1'b1;
    end else begin
        weights_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_13_ce0_local = 1'b1;
    end else begin
        weights_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_14_ce0_local = 1'b1;
    end else begin
        weights_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_15_ce0_local = 1'b1;
    end else begin
        weights_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_16_ce0_local = 1'b1;
    end else begin
        weights_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_17_ce0_local = 1'b1;
    end else begin
        weights_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_18_ce0_local = 1'b1;
    end else begin
        weights_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_19_ce0_local = 1'b1;
    end else begin
        weights_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weights_1_ce0_local = 1'b1;
    end else begin
        weights_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_20_ce0_local = 1'b1;
    end else begin
        weights_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_21_ce0_local = 1'b1;
    end else begin
        weights_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_22_ce0_local = 1'b1;
    end else begin
        weights_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_23_ce0_local = 1'b1;
    end else begin
        weights_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_24_ce0_local = 1'b1;
    end else begin
        weights_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_25_ce0_local = 1'b1;
    end else begin
        weights_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_26_ce0_local = 1'b1;
    end else begin
        weights_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_27_ce0_local = 1'b1;
    end else begin
        weights_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_28_ce0_local = 1'b1;
    end else begin
        weights_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_29_ce0_local = 1'b1;
    end else begin
        weights_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weights_2_ce0_local = 1'b1;
    end else begin
        weights_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_30_ce0_local = 1'b1;
    end else begin
        weights_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_31_ce0_local = 1'b1;
    end else begin
        weights_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weights_3_ce0_local = 1'b1;
    end else begin
        weights_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_4_ce0_local = 1'b1;
    end else begin
        weights_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_5_ce0_local = 1'b1;
    end else begin
        weights_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_6_ce0_local = 1'b1;
    end else begin
        weights_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_7_ce0_local = 1'b1;
    end else begin
        weights_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weights_8_ce0_local = 1'b1;
    end else begin
        weights_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weights_9_ce0_local = 1'b1;
    end else begin
        weights_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln30_fu_1107_p2 = (ap_sig_allocacmp_i_1 + 31'd1);

assign add_ln36_10_fu_1154_p2 = (mul_ln36_19_reg_1890 + mul_ln36_18_reg_1885);

assign add_ln36_11_fu_1158_p2 = (mul_ln36_17_reg_1880 + mul_ln36_16_reg_1875);

assign add_ln36_12_fu_1162_p2 = (add_ln36_11_fu_1158_p2 + add_ln36_10_fu_1154_p2);

assign add_ln36_13_fu_1248_p2 = (add_ln36_12_reg_1965 + add_ln36_9_fu_1242_p2);

assign add_ln36_14_fu_1262_p2 = (add_ln36_13_reg_1990 + add_ln36_6_reg_1985);

assign add_ln36_15_fu_1168_p2 = (mul_ln36_15_reg_1870 + mul_ln36_14_reg_1865);

assign add_ln36_16_fu_1172_p2 = (mul_ln36_13_reg_1860 + mul_ln36_12_reg_1855);

assign add_ln36_17_fu_1176_p2 = (add_ln36_16_fu_1172_p2 + add_ln36_15_fu_1168_p2);

assign add_ln36_18_fu_1182_p2 = (mul_ln36_11_reg_1850 + mul_ln36_10_reg_1845);

assign add_ln36_19_fu_1186_p2 = (mul_ln36_9_reg_1840 + mul_ln36_8_reg_1835);

assign add_ln36_1_fu_1219_p2 = (mul_ln36_29_reg_1945 + mul_ln36_28_reg_1940);

assign add_ln36_20_fu_1190_p2 = (add_ln36_19_fu_1186_p2 + add_ln36_18_fu_1182_p2);

assign add_ln36_21_fu_1253_p2 = (add_ln36_20_reg_1975 + add_ln36_17_reg_1970);

assign add_ln36_22_fu_1196_p2 = (mul_ln36_7_reg_1830 + mul_ln36_6_reg_1825);

assign add_ln36_23_fu_1200_p2 = (mul_ln36_5_reg_1820 + mul_ln36_4_reg_1815);

assign add_ln36_24_fu_1204_p2 = (add_ln36_23_fu_1200_p2 + add_ln36_22_fu_1196_p2);

assign add_ln36_25_fu_1126_p2 = (mul_ln36_3_reg_1770 + mul_ln36_2_reg_1765);

assign add_ln36_26_fu_1130_p2 = (mul_ln36_1_reg_1760 + mul_ln36_reg_1755);

assign add_ln36_27_fu_1134_p2 = (add_ln36_26_fu_1130_p2 + add_ln36_25_fu_1126_p2);

assign add_ln36_28_fu_1210_p2 = (add_ln36_27_reg_1915 + add_ln36_24_fu_1204_p2);

assign add_ln36_29_fu_1257_p2 = (add_ln36_28_reg_1980 + add_ln36_21_fu_1253_p2);

assign add_ln36_2_fu_1223_p2 = (add_ln36_1_fu_1219_p2 + add_ln36_fu_1215_p2);

assign add_ln36_3_fu_1140_p2 = (mul_ln36_27_reg_1910 + mul_ln36_26_reg_1905);

assign add_ln36_4_fu_1144_p2 = (mul_ln36_25_reg_1900 + mul_ln36_24_reg_1895);

assign add_ln36_5_fu_1148_p2 = (add_ln36_4_fu_1144_p2 + add_ln36_3_fu_1140_p2);

assign add_ln36_6_fu_1229_p2 = (add_ln36_5_reg_1960 + add_ln36_2_fu_1223_p2);

assign add_ln36_7_fu_1234_p2 = (mul_ln36_23_reg_1935 + mul_ln36_22_reg_1930);

assign add_ln36_8_fu_1238_p2 = (mul_ln36_21_reg_1925 + mul_ln36_20_reg_1920);

assign add_ln36_9_fu_1242_p2 = (add_ln36_8_fu_1238_p2 + add_ln36_7_fu_1234_p2);

assign add_ln36_fu_1215_p2 = (mul_ln36_31_reg_1955 + mul_ln36_30_reg_1950);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((out_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_801_p1 = sext_ln36_31_cast_reg_1434;

assign grp_fu_806_p1 = sext_ln36_30_cast_reg_1429;

assign grp_fu_811_p1 = sext_ln36_29_cast_reg_1424;

assign grp_fu_816_p1 = sext_ln36_28_cast_reg_1419;

assign grp_fu_821_p1 = sext_ln36_27_cast_reg_1414;

assign grp_fu_826_p1 = sext_ln36_26_cast_reg_1409;

assign grp_fu_831_p1 = sext_ln36_25_cast_reg_1404;

assign grp_fu_836_p1 = sext_ln36_24_cast_reg_1399;

assign grp_fu_841_p1 = sext_ln36_23_cast_reg_1394;

assign grp_fu_846_p1 = sext_ln36_22_cast_reg_1389;

assign grp_fu_851_p1 = sext_ln36_21_cast_reg_1384;

assign grp_fu_856_p1 = sext_ln36_20_cast_reg_1379;

assign grp_fu_861_p1 = sext_ln36_19_cast_reg_1374;

assign grp_fu_866_p1 = sext_ln36_18_cast_reg_1369;

assign grp_fu_871_p1 = sext_ln36_17_cast_reg_1364;

assign grp_fu_876_p1 = sext_ln36_16_cast_reg_1359;

assign grp_fu_881_p1 = sext_ln36_15_cast_reg_1354;

assign grp_fu_886_p1 = sext_ln36_14_cast_reg_1349;

assign grp_fu_891_p1 = sext_ln36_13_cast_reg_1344;

assign grp_fu_896_p1 = sext_ln36_12_cast_reg_1339;

assign grp_fu_901_p1 = sext_ln36_7_cast_reg_1314;

assign grp_fu_906_p1 = sext_ln36_6_cast_reg_1309;

assign grp_fu_911_p1 = sext_ln36_5_cast_reg_1304;

assign grp_fu_916_p1 = sext_ln36_4_cast_reg_1299;

assign grp_fu_921_p1 = sext_ln36_11_cast_reg_1334;

assign grp_fu_926_p1 = sext_ln36_10_cast_reg_1329;

assign grp_fu_931_p1 = sext_ln36_9_cast_reg_1324;

assign grp_fu_936_p1 = sext_ln36_8_cast_reg_1319;

assign grp_fu_941_p1 = sext_ln36_3_cast_reg_1294;

assign grp_fu_946_p1 = sext_ln36_2_cast_reg_1289;

assign grp_fu_951_p1 = sext_ln36_cast_reg_1284;

assign grp_fu_956_p1 = sext_ln36_1_cast_reg_1279;

assign icmp_ln30_fu_1101_p2 = (($signed(zext_ln30_1_fu_1097_p1) < $signed(num_rows)) ? 1'b1 : 1'b0);

assign out_stream_TDATA = (add_ln36_29_reg_1995 + add_ln36_14_fu_1262_p2);

assign sext_ln36_10_cast_fu_1001_p1 = $signed(sext_ln36_10);

assign sext_ln36_11_cast_fu_1005_p1 = $signed(sext_ln36_11);

assign sext_ln36_12_cast_fu_1009_p1 = $signed(sext_ln36_12);

assign sext_ln36_13_cast_fu_1013_p1 = $signed(sext_ln36_13);

assign sext_ln36_14_cast_fu_1017_p1 = $signed(sext_ln36_14);

assign sext_ln36_15_cast_fu_1021_p1 = $signed(sext_ln36_15);

assign sext_ln36_16_cast_fu_1025_p1 = $signed(sext_ln36_16);

assign sext_ln36_17_cast_fu_1029_p1 = $signed(sext_ln36_17);

assign sext_ln36_18_cast_fu_1033_p1 = $signed(sext_ln36_18);

assign sext_ln36_19_cast_fu_1037_p1 = $signed(sext_ln36_19);

assign sext_ln36_1_cast_fu_961_p1 = $signed(sext_ln36_1);

assign sext_ln36_20_cast_fu_1041_p1 = $signed(sext_ln36_20);

assign sext_ln36_21_cast_fu_1045_p1 = $signed(sext_ln36_21);

assign sext_ln36_22_cast_fu_1049_p1 = $signed(sext_ln36_22);

assign sext_ln36_23_cast_fu_1053_p1 = $signed(sext_ln36_23);

assign sext_ln36_24_cast_fu_1057_p1 = $signed(sext_ln36_24);

assign sext_ln36_25_cast_fu_1061_p1 = $signed(sext_ln36_25);

assign sext_ln36_26_cast_fu_1065_p1 = $signed(sext_ln36_26);

assign sext_ln36_27_cast_fu_1069_p1 = $signed(sext_ln36_27);

assign sext_ln36_28_cast_fu_1073_p1 = $signed(sext_ln36_28);

assign sext_ln36_29_cast_fu_1077_p1 = $signed(sext_ln36_29);

assign sext_ln36_2_cast_fu_969_p1 = $signed(sext_ln36_2);

assign sext_ln36_30_cast_fu_1081_p1 = $signed(sext_ln36_30);

assign sext_ln36_31_cast_fu_1085_p1 = $signed(sext_ln36_31);

assign sext_ln36_3_cast_fu_973_p1 = $signed(sext_ln36_3);

assign sext_ln36_4_cast_fu_977_p1 = $signed(sext_ln36_4);

assign sext_ln36_5_cast_fu_981_p1 = $signed(sext_ln36_5);

assign sext_ln36_6_cast_fu_985_p1 = $signed(sext_ln36_6);

assign sext_ln36_7_cast_fu_989_p1 = $signed(sext_ln36_7);

assign sext_ln36_8_cast_fu_993_p1 = $signed(sext_ln36_8);

assign sext_ln36_9_cast_fu_997_p1 = $signed(sext_ln36_9);

assign sext_ln36_cast_fu_965_p1 = $signed(sext_ln36);

assign weights_0_address0 = zext_ln30_reg_1443_pp0_iter1_reg;

assign weights_0_ce0 = weights_0_ce0_local;

assign weights_10_address0 = zext_ln30_reg_1443_pp0_iter1_reg;

assign weights_10_ce0 = weights_10_ce0_local;

assign weights_11_address0 = zext_ln30_reg_1443_pp0_iter1_reg;

assign weights_11_ce0 = weights_11_ce0_local;

assign weights_12_address0 = zext_ln30_reg_1443;

assign weights_12_ce0 = weights_12_ce0_local;

assign weights_13_address0 = zext_ln30_reg_1443;

assign weights_13_ce0 = weights_13_ce0_local;

assign weights_14_address0 = zext_ln30_reg_1443;

assign weights_14_ce0 = weights_14_ce0_local;

assign weights_15_address0 = zext_ln30_reg_1443;

assign weights_15_ce0 = weights_15_ce0_local;

assign weights_16_address0 = zext_ln30_reg_1443;

assign weights_16_ce0 = weights_16_ce0_local;

assign weights_17_address0 = zext_ln30_reg_1443;

assign weights_17_ce0 = weights_17_ce0_local;

assign weights_18_address0 = zext_ln30_reg_1443;

assign weights_18_ce0 = weights_18_ce0_local;

assign weights_19_address0 = zext_ln30_reg_1443;

assign weights_19_ce0 = weights_19_ce0_local;

assign weights_1_address0 = zext_ln30_reg_1443_pp0_iter1_reg;

assign weights_1_ce0 = weights_1_ce0_local;

assign weights_20_address0 = zext_ln30_reg_1443;

assign weights_20_ce0 = weights_20_ce0_local;

assign weights_21_address0 = zext_ln30_reg_1443;

assign weights_21_ce0 = weights_21_ce0_local;

assign weights_22_address0 = zext_ln30_reg_1443;

assign weights_22_ce0 = weights_22_ce0_local;

assign weights_23_address0 = zext_ln30_reg_1443;

assign weights_23_ce0 = weights_23_ce0_local;

assign weights_24_address0 = zext_ln30_reg_1443;

assign weights_24_ce0 = weights_24_ce0_local;

assign weights_25_address0 = zext_ln30_reg_1443;

assign weights_25_ce0 = weights_25_ce0_local;

assign weights_26_address0 = zext_ln30_reg_1443;

assign weights_26_ce0 = weights_26_ce0_local;

assign weights_27_address0 = zext_ln30_reg_1443;

assign weights_27_ce0 = weights_27_ce0_local;

assign weights_28_address0 = zext_ln30_fu_1113_p1;

assign weights_28_ce0 = weights_28_ce0_local;

assign weights_29_address0 = zext_ln30_fu_1113_p1;

assign weights_29_ce0 = weights_29_ce0_local;

assign weights_2_address0 = zext_ln30_reg_1443_pp0_iter1_reg;

assign weights_2_ce0 = weights_2_ce0_local;

assign weights_30_address0 = zext_ln30_fu_1113_p1;

assign weights_30_ce0 = weights_30_ce0_local;

assign weights_31_address0 = zext_ln30_fu_1113_p1;

assign weights_31_ce0 = weights_31_ce0_local;

assign weights_3_address0 = zext_ln30_reg_1443_pp0_iter1_reg;

assign weights_3_ce0 = weights_3_ce0_local;

assign weights_4_address0 = zext_ln30_reg_1443;

assign weights_4_ce0 = weights_4_ce0_local;

assign weights_5_address0 = zext_ln30_reg_1443;

assign weights_5_ce0 = weights_5_ce0_local;

assign weights_6_address0 = zext_ln30_reg_1443;

assign weights_6_ce0 = weights_6_ce0_local;

assign weights_7_address0 = zext_ln30_reg_1443;

assign weights_7_ce0 = weights_7_ce0_local;

assign weights_8_address0 = zext_ln30_reg_1443_pp0_iter1_reg;

assign weights_8_ce0 = weights_8_ce0_local;

assign weights_9_address0 = zext_ln30_reg_1443_pp0_iter1_reg;

assign weights_9_ce0 = weights_9_ce0_local;

assign zext_ln30_1_fu_1097_p1 = ap_sig_allocacmp_i_1;

assign zext_ln30_fu_1113_p1 = ap_sig_allocacmp_i_1;

always @ (posedge ap_clk) begin
    zext_ln30_reg_1443[63:31] <= 33'b000000000000000000000000000000000;
    zext_ln30_reg_1443_pp0_iter1_reg[63:31] <= 33'b000000000000000000000000000000000;
end

endmodule //dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_30_2
