-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_30_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    num_rows : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_0_ce0 : OUT STD_LOGIC;
    weights_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_1_ce0 : OUT STD_LOGIC;
    weights_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_2_ce0 : OUT STD_LOGIC;
    weights_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_3_ce0 : OUT STD_LOGIC;
    weights_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_4_ce0 : OUT STD_LOGIC;
    weights_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_5_ce0 : OUT STD_LOGIC;
    weights_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_6_ce0 : OUT STD_LOGIC;
    weights_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_7_ce0 : OUT STD_LOGIC;
    weights_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_8_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_8_ce0 : OUT STD_LOGIC;
    weights_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_9_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_9_ce0 : OUT STD_LOGIC;
    weights_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_10_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_10_ce0 : OUT STD_LOGIC;
    weights_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_11_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_11_ce0 : OUT STD_LOGIC;
    weights_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_12_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_12_ce0 : OUT STD_LOGIC;
    weights_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_13_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_13_ce0 : OUT STD_LOGIC;
    weights_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_14_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_14_ce0 : OUT STD_LOGIC;
    weights_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_15_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_15_ce0 : OUT STD_LOGIC;
    weights_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_16_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_16_ce0 : OUT STD_LOGIC;
    weights_16_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_17_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_17_ce0 : OUT STD_LOGIC;
    weights_17_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_18_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_18_ce0 : OUT STD_LOGIC;
    weights_18_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_19_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_19_ce0 : OUT STD_LOGIC;
    weights_19_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_20_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_20_ce0 : OUT STD_LOGIC;
    weights_20_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_21_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_21_ce0 : OUT STD_LOGIC;
    weights_21_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_22_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_22_ce0 : OUT STD_LOGIC;
    weights_22_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_23_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_23_ce0 : OUT STD_LOGIC;
    weights_23_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_24_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_24_ce0 : OUT STD_LOGIC;
    weights_24_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_25_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_25_ce0 : OUT STD_LOGIC;
    weights_25_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_26_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_26_ce0 : OUT STD_LOGIC;
    weights_26_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_27_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_27_ce0 : OUT STD_LOGIC;
    weights_27_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_28_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_28_ce0 : OUT STD_LOGIC;
    weights_28_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_29_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_29_ce0 : OUT STD_LOGIC;
    weights_29_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_30_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_30_ce0 : OUT STD_LOGIC;
    weights_30_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_31_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    weights_31_ce0 : OUT STD_LOGIC;
    weights_31_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln36_31 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_30 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_29 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_28 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_27 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_26 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_25 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_24 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_23 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_22 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_21 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_20 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_19 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_18 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_17 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_16 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_15 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_14 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_13 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_12 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_11 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_10 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_9 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_8 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_7 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_6 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36 : IN STD_LOGIC_VECTOR (7 downto 0);
    sext_ln36_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC );
end;


architecture behav of dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_30_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln30_fu_1101_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal sext_ln36_1_cast_fu_961_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_1_cast_reg_1279 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal sext_ln36_cast_fu_965_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_cast_reg_1284 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_2_cast_fu_969_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_2_cast_reg_1289 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_3_cast_fu_973_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_3_cast_reg_1294 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_4_cast_fu_977_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_4_cast_reg_1299 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_5_cast_fu_981_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_5_cast_reg_1304 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_6_cast_fu_985_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_6_cast_reg_1309 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_7_cast_fu_989_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_7_cast_reg_1314 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_8_cast_fu_993_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_8_cast_reg_1319 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_9_cast_fu_997_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_9_cast_reg_1324 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_10_cast_fu_1001_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_10_cast_reg_1329 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_11_cast_fu_1005_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_11_cast_reg_1334 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_12_cast_fu_1009_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_12_cast_reg_1339 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_13_cast_fu_1013_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_13_cast_reg_1344 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_14_cast_fu_1017_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_14_cast_reg_1349 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_15_cast_fu_1021_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_15_cast_reg_1354 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_16_cast_fu_1025_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_16_cast_reg_1359 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_17_cast_fu_1029_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_17_cast_reg_1364 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_18_cast_fu_1033_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_18_cast_reg_1369 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_19_cast_fu_1037_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_19_cast_reg_1374 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_20_cast_fu_1041_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_20_cast_reg_1379 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_21_cast_fu_1045_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_21_cast_reg_1384 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_22_cast_fu_1049_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_22_cast_reg_1389 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_23_cast_fu_1053_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_23_cast_reg_1394 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_24_cast_fu_1057_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_24_cast_reg_1399 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_25_cast_fu_1061_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_25_cast_reg_1404 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_26_cast_fu_1065_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_26_cast_reg_1409 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_27_cast_fu_1069_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_27_cast_reg_1414 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_28_cast_fu_1073_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_28_cast_reg_1419 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln36_29_cast_fu_1077_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_29_cast_reg_1424 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_30_cast_fu_1081_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_30_cast_reg_1429 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_31_cast_fu_1085_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_31_cast_reg_1434 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln30_fu_1113_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln30_reg_1443 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln30_reg_1443_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_801_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_reg_1755 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_806_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_1_reg_1760 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_811_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_2_reg_1765 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_816_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_3_reg_1770 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_821_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_4_reg_1815 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_826_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_5_reg_1820 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_831_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_6_reg_1825 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_836_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_7_reg_1830 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_841_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_8_reg_1835 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_846_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_9_reg_1840 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_851_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_10_reg_1845 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_856_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_11_reg_1850 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_861_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_12_reg_1855 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_866_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_13_reg_1860 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_871_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_14_reg_1865 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_876_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_15_reg_1870 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_881_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_16_reg_1875 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_886_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_17_reg_1880 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_891_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_18_reg_1885 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_896_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_19_reg_1890 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_901_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_24_reg_1895 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_906_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_25_reg_1900 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_911_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_26_reg_1905 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_916_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_27_reg_1910 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_27_fu_1134_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_27_reg_1915 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_921_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_20_reg_1920 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_926_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_21_reg_1925 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_931_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_22_reg_1930 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_936_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_23_reg_1935 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_941_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_28_reg_1940 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_946_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_29_reg_1945 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_951_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_30_reg_1950 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_956_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln36_31_reg_1955 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_5_fu_1148_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_5_reg_1960 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_12_fu_1162_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_12_reg_1965 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_17_fu_1176_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_17_reg_1970 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_20_fu_1190_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_20_reg_1975 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_28_fu_1210_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_28_reg_1980 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_6_fu_1229_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_6_reg_1985 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_13_fu_1248_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_13_reg_1990 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_29_fu_1257_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_29_reg_1995 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_176 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln30_fu_1107_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal weights_28_ce0_local : STD_LOGIC;
    signal weights_29_ce0_local : STD_LOGIC;
    signal weights_30_ce0_local : STD_LOGIC;
    signal weights_31_ce0_local : STD_LOGIC;
    signal weights_4_ce0_local : STD_LOGIC;
    signal weights_5_ce0_local : STD_LOGIC;
    signal weights_6_ce0_local : STD_LOGIC;
    signal weights_7_ce0_local : STD_LOGIC;
    signal weights_12_ce0_local : STD_LOGIC;
    signal weights_13_ce0_local : STD_LOGIC;
    signal weights_14_ce0_local : STD_LOGIC;
    signal weights_15_ce0_local : STD_LOGIC;
    signal weights_16_ce0_local : STD_LOGIC;
    signal weights_17_ce0_local : STD_LOGIC;
    signal weights_18_ce0_local : STD_LOGIC;
    signal weights_19_ce0_local : STD_LOGIC;
    signal weights_20_ce0_local : STD_LOGIC;
    signal weights_21_ce0_local : STD_LOGIC;
    signal weights_22_ce0_local : STD_LOGIC;
    signal weights_23_ce0_local : STD_LOGIC;
    signal weights_24_ce0_local : STD_LOGIC;
    signal weights_25_ce0_local : STD_LOGIC;
    signal weights_26_ce0_local : STD_LOGIC;
    signal weights_27_ce0_local : STD_LOGIC;
    signal weights_0_ce0_local : STD_LOGIC;
    signal weights_1_ce0_local : STD_LOGIC;
    signal weights_2_ce0_local : STD_LOGIC;
    signal weights_3_ce0_local : STD_LOGIC;
    signal weights_8_ce0_local : STD_LOGIC;
    signal weights_9_ce0_local : STD_LOGIC;
    signal weights_10_ce0_local : STD_LOGIC;
    signal weights_11_ce0_local : STD_LOGIC;
    signal grp_fu_801_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_806_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_811_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_816_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_821_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_826_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_831_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_836_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_841_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_846_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_851_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_856_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_861_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_866_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_871_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_876_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_881_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_886_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_891_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_896_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_901_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_906_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_911_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_916_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_921_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_926_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_931_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_936_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_941_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_946_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_951_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_956_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln30_1_fu_1097_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_26_fu_1130_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_25_fu_1126_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_4_fu_1144_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_3_fu_1140_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_11_fu_1158_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_10_fu_1154_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_16_fu_1172_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_15_fu_1168_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_19_fu_1186_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_18_fu_1182_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_23_fu_1200_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_22_fu_1196_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_24_fu_1204_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_1_fu_1219_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_fu_1215_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_2_fu_1223_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_8_fu_1238_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_7_fu_1234_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_9_fu_1242_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_21_fu_1253_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln36_14_fu_1262_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_801_ce : STD_LOGIC;
    signal grp_fu_806_ce : STD_LOGIC;
    signal grp_fu_811_ce : STD_LOGIC;
    signal grp_fu_816_ce : STD_LOGIC;
    signal grp_fu_821_ce : STD_LOGIC;
    signal grp_fu_826_ce : STD_LOGIC;
    signal grp_fu_831_ce : STD_LOGIC;
    signal grp_fu_836_ce : STD_LOGIC;
    signal grp_fu_841_ce : STD_LOGIC;
    signal grp_fu_846_ce : STD_LOGIC;
    signal grp_fu_851_ce : STD_LOGIC;
    signal grp_fu_856_ce : STD_LOGIC;
    signal grp_fu_861_ce : STD_LOGIC;
    signal grp_fu_866_ce : STD_LOGIC;
    signal grp_fu_871_ce : STD_LOGIC;
    signal grp_fu_876_ce : STD_LOGIC;
    signal grp_fu_881_ce : STD_LOGIC;
    signal grp_fu_886_ce : STD_LOGIC;
    signal grp_fu_891_ce : STD_LOGIC;
    signal grp_fu_896_ce : STD_LOGIC;
    signal grp_fu_901_ce : STD_LOGIC;
    signal grp_fu_906_ce : STD_LOGIC;
    signal grp_fu_911_ce : STD_LOGIC;
    signal grp_fu_916_ce : STD_LOGIC;
    signal grp_fu_921_ce : STD_LOGIC;
    signal grp_fu_926_ce : STD_LOGIC;
    signal grp_fu_931_ce : STD_LOGIC;
    signal grp_fu_936_ce : STD_LOGIC;
    signal grp_fu_941_ce : STD_LOGIC;
    signal grp_fu_946_ce : STD_LOGIC;
    signal grp_fu_951_ce : STD_LOGIC;
    signal grp_fu_956_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dense_gemv_mul_32s_8s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dense_gemv_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_8s_32_2_1_U34 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_31_q0,
        din1 => grp_fu_801_p1,
        ce => grp_fu_801_ce,
        dout => grp_fu_801_p2);

    mul_32s_8s_32_2_1_U35 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_30_q0,
        din1 => grp_fu_806_p1,
        ce => grp_fu_806_ce,
        dout => grp_fu_806_p2);

    mul_32s_8s_32_2_1_U36 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_29_q0,
        din1 => grp_fu_811_p1,
        ce => grp_fu_811_ce,
        dout => grp_fu_811_p2);

    mul_32s_8s_32_2_1_U37 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_28_q0,
        din1 => grp_fu_816_p1,
        ce => grp_fu_816_ce,
        dout => grp_fu_816_p2);

    mul_32s_8s_32_2_1_U38 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_27_q0,
        din1 => grp_fu_821_p1,
        ce => grp_fu_821_ce,
        dout => grp_fu_821_p2);

    mul_32s_8s_32_2_1_U39 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_26_q0,
        din1 => grp_fu_826_p1,
        ce => grp_fu_826_ce,
        dout => grp_fu_826_p2);

    mul_32s_8s_32_2_1_U40 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_25_q0,
        din1 => grp_fu_831_p1,
        ce => grp_fu_831_ce,
        dout => grp_fu_831_p2);

    mul_32s_8s_32_2_1_U41 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_24_q0,
        din1 => grp_fu_836_p1,
        ce => grp_fu_836_ce,
        dout => grp_fu_836_p2);

    mul_32s_8s_32_2_1_U42 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_23_q0,
        din1 => grp_fu_841_p1,
        ce => grp_fu_841_ce,
        dout => grp_fu_841_p2);

    mul_32s_8s_32_2_1_U43 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_22_q0,
        din1 => grp_fu_846_p1,
        ce => grp_fu_846_ce,
        dout => grp_fu_846_p2);

    mul_32s_8s_32_2_1_U44 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_21_q0,
        din1 => grp_fu_851_p1,
        ce => grp_fu_851_ce,
        dout => grp_fu_851_p2);

    mul_32s_8s_32_2_1_U45 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_20_q0,
        din1 => grp_fu_856_p1,
        ce => grp_fu_856_ce,
        dout => grp_fu_856_p2);

    mul_32s_8s_32_2_1_U46 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_19_q0,
        din1 => grp_fu_861_p1,
        ce => grp_fu_861_ce,
        dout => grp_fu_861_p2);

    mul_32s_8s_32_2_1_U47 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_18_q0,
        din1 => grp_fu_866_p1,
        ce => grp_fu_866_ce,
        dout => grp_fu_866_p2);

    mul_32s_8s_32_2_1_U48 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_17_q0,
        din1 => grp_fu_871_p1,
        ce => grp_fu_871_ce,
        dout => grp_fu_871_p2);

    mul_32s_8s_32_2_1_U49 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_16_q0,
        din1 => grp_fu_876_p1,
        ce => grp_fu_876_ce,
        dout => grp_fu_876_p2);

    mul_32s_8s_32_2_1_U50 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_15_q0,
        din1 => grp_fu_881_p1,
        ce => grp_fu_881_ce,
        dout => grp_fu_881_p2);

    mul_32s_8s_32_2_1_U51 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_14_q0,
        din1 => grp_fu_886_p1,
        ce => grp_fu_886_ce,
        dout => grp_fu_886_p2);

    mul_32s_8s_32_2_1_U52 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_13_q0,
        din1 => grp_fu_891_p1,
        ce => grp_fu_891_ce,
        dout => grp_fu_891_p2);

    mul_32s_8s_32_2_1_U53 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_12_q0,
        din1 => grp_fu_896_p1,
        ce => grp_fu_896_ce,
        dout => grp_fu_896_p2);

    mul_32s_8s_32_2_1_U54 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_7_q0,
        din1 => grp_fu_901_p1,
        ce => grp_fu_901_ce,
        dout => grp_fu_901_p2);

    mul_32s_8s_32_2_1_U55 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_6_q0,
        din1 => grp_fu_906_p1,
        ce => grp_fu_906_ce,
        dout => grp_fu_906_p2);

    mul_32s_8s_32_2_1_U56 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_5_q0,
        din1 => grp_fu_911_p1,
        ce => grp_fu_911_ce,
        dout => grp_fu_911_p2);

    mul_32s_8s_32_2_1_U57 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_4_q0,
        din1 => grp_fu_916_p1,
        ce => grp_fu_916_ce,
        dout => grp_fu_916_p2);

    mul_32s_8s_32_2_1_U58 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_11_q0,
        din1 => grp_fu_921_p1,
        ce => grp_fu_921_ce,
        dout => grp_fu_921_p2);

    mul_32s_8s_32_2_1_U59 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_10_q0,
        din1 => grp_fu_926_p1,
        ce => grp_fu_926_ce,
        dout => grp_fu_926_p2);

    mul_32s_8s_32_2_1_U60 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_9_q0,
        din1 => grp_fu_931_p1,
        ce => grp_fu_931_ce,
        dout => grp_fu_931_p2);

    mul_32s_8s_32_2_1_U61 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_8_q0,
        din1 => grp_fu_936_p1,
        ce => grp_fu_936_ce,
        dout => grp_fu_936_p2);

    mul_32s_8s_32_2_1_U62 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_3_q0,
        din1 => grp_fu_941_p1,
        ce => grp_fu_941_ce,
        dout => grp_fu_941_p2);

    mul_32s_8s_32_2_1_U63 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_2_q0,
        din1 => grp_fu_946_p1,
        ce => grp_fu_946_ce,
        dout => grp_fu_946_p2);

    mul_32s_8s_32_2_1_U64 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_0_q0,
        din1 => grp_fu_951_p1,
        ce => grp_fu_951_ce,
        dout => grp_fu_951_p2);

    mul_32s_8s_32_2_1_U65 : component dense_gemv_mul_32s_8s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => weights_1_q0,
        din1 => grp_fu_956_p1,
        ce => grp_fu_956_ce,
        dout => grp_fu_956_p2);

    flow_control_loop_pipe_sequential_init_U : component dense_gemv_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    i_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln30_fu_1101_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_176 <= add_ln30_fu_1107_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_176 <= ap_const_lv31_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln36_12_reg_1965 <= add_ln36_12_fu_1162_p2;
                add_ln36_13_reg_1990 <= add_ln36_13_fu_1248_p2;
                add_ln36_17_reg_1970 <= add_ln36_17_fu_1176_p2;
                add_ln36_20_reg_1975 <= add_ln36_20_fu_1190_p2;
                add_ln36_27_reg_1915 <= add_ln36_27_fu_1134_p2;
                add_ln36_28_reg_1980 <= add_ln36_28_fu_1210_p2;
                add_ln36_29_reg_1995 <= add_ln36_29_fu_1257_p2;
                add_ln36_5_reg_1960 <= add_ln36_5_fu_1148_p2;
                add_ln36_6_reg_1985 <= add_ln36_6_fu_1229_p2;
                mul_ln36_10_reg_1845 <= grp_fu_851_p2;
                mul_ln36_11_reg_1850 <= grp_fu_856_p2;
                mul_ln36_12_reg_1855 <= grp_fu_861_p2;
                mul_ln36_13_reg_1860 <= grp_fu_866_p2;
                mul_ln36_14_reg_1865 <= grp_fu_871_p2;
                mul_ln36_15_reg_1870 <= grp_fu_876_p2;
                mul_ln36_16_reg_1875 <= grp_fu_881_p2;
                mul_ln36_17_reg_1880 <= grp_fu_886_p2;
                mul_ln36_18_reg_1885 <= grp_fu_891_p2;
                mul_ln36_19_reg_1890 <= grp_fu_896_p2;
                mul_ln36_20_reg_1920 <= grp_fu_921_p2;
                mul_ln36_21_reg_1925 <= grp_fu_926_p2;
                mul_ln36_22_reg_1930 <= grp_fu_931_p2;
                mul_ln36_23_reg_1935 <= grp_fu_936_p2;
                mul_ln36_24_reg_1895 <= grp_fu_901_p2;
                mul_ln36_25_reg_1900 <= grp_fu_906_p2;
                mul_ln36_26_reg_1905 <= grp_fu_911_p2;
                mul_ln36_27_reg_1910 <= grp_fu_916_p2;
                mul_ln36_28_reg_1940 <= grp_fu_941_p2;
                mul_ln36_29_reg_1945 <= grp_fu_946_p2;
                mul_ln36_30_reg_1950 <= grp_fu_951_p2;
                mul_ln36_31_reg_1955 <= grp_fu_956_p2;
                mul_ln36_4_reg_1815 <= grp_fu_821_p2;
                mul_ln36_5_reg_1820 <= grp_fu_826_p2;
                mul_ln36_6_reg_1825 <= grp_fu_831_p2;
                mul_ln36_7_reg_1830 <= grp_fu_836_p2;
                mul_ln36_8_reg_1835 <= grp_fu_841_p2;
                mul_ln36_9_reg_1840 <= grp_fu_846_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                sext_ln36_28_cast_reg_1419 <= sext_ln36_28_cast_fu_1073_p1;
                sext_ln36_29_cast_reg_1424 <= sext_ln36_29_cast_fu_1077_p1;
                sext_ln36_30_cast_reg_1429 <= sext_ln36_30_cast_fu_1081_p1;
                sext_ln36_31_cast_reg_1434 <= sext_ln36_31_cast_fu_1085_p1;
                    zext_ln30_reg_1443(30 downto 0) <= zext_ln30_fu_1113_p1(30 downto 0);
                    zext_ln30_reg_1443_pp0_iter1_reg(30 downto 0) <= zext_ln30_reg_1443(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                mul_ln36_1_reg_1760 <= grp_fu_806_p2;
                mul_ln36_2_reg_1765 <= grp_fu_811_p2;
                mul_ln36_3_reg_1770 <= grp_fu_816_p2;
                mul_ln36_reg_1755 <= grp_fu_801_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                sext_ln36_10_cast_reg_1329 <= sext_ln36_10_cast_fu_1001_p1;
                sext_ln36_11_cast_reg_1334 <= sext_ln36_11_cast_fu_1005_p1;
                sext_ln36_12_cast_reg_1339 <= sext_ln36_12_cast_fu_1009_p1;
                sext_ln36_13_cast_reg_1344 <= sext_ln36_13_cast_fu_1013_p1;
                sext_ln36_14_cast_reg_1349 <= sext_ln36_14_cast_fu_1017_p1;
                sext_ln36_15_cast_reg_1354 <= sext_ln36_15_cast_fu_1021_p1;
                sext_ln36_16_cast_reg_1359 <= sext_ln36_16_cast_fu_1025_p1;
                sext_ln36_17_cast_reg_1364 <= sext_ln36_17_cast_fu_1029_p1;
                sext_ln36_18_cast_reg_1369 <= sext_ln36_18_cast_fu_1033_p1;
                sext_ln36_19_cast_reg_1374 <= sext_ln36_19_cast_fu_1037_p1;
                sext_ln36_1_cast_reg_1279 <= sext_ln36_1_cast_fu_961_p1;
                sext_ln36_20_cast_reg_1379 <= sext_ln36_20_cast_fu_1041_p1;
                sext_ln36_21_cast_reg_1384 <= sext_ln36_21_cast_fu_1045_p1;
                sext_ln36_22_cast_reg_1389 <= sext_ln36_22_cast_fu_1049_p1;
                sext_ln36_23_cast_reg_1394 <= sext_ln36_23_cast_fu_1053_p1;
                sext_ln36_24_cast_reg_1399 <= sext_ln36_24_cast_fu_1057_p1;
                sext_ln36_25_cast_reg_1404 <= sext_ln36_25_cast_fu_1061_p1;
                sext_ln36_26_cast_reg_1409 <= sext_ln36_26_cast_fu_1065_p1;
                sext_ln36_27_cast_reg_1414 <= sext_ln36_27_cast_fu_1069_p1;
                sext_ln36_2_cast_reg_1289 <= sext_ln36_2_cast_fu_969_p1;
                sext_ln36_3_cast_reg_1294 <= sext_ln36_3_cast_fu_973_p1;
                sext_ln36_4_cast_reg_1299 <= sext_ln36_4_cast_fu_977_p1;
                sext_ln36_5_cast_reg_1304 <= sext_ln36_5_cast_fu_981_p1;
                sext_ln36_6_cast_reg_1309 <= sext_ln36_6_cast_fu_985_p1;
                sext_ln36_7_cast_reg_1314 <= sext_ln36_7_cast_fu_989_p1;
                sext_ln36_8_cast_reg_1319 <= sext_ln36_8_cast_fu_993_p1;
                sext_ln36_9_cast_reg_1324 <= sext_ln36_9_cast_fu_997_p1;
                sext_ln36_cast_reg_1284 <= sext_ln36_cast_fu_965_p1;
            end if;
        end if;
    end process;
    zext_ln30_reg_1443(63 downto 31) <= "000000000000000000000000000000000";
    zext_ln30_reg_1443_pp0_iter1_reg(63 downto 31) <= "000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln30_fu_1107_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv31_1));
    add_ln36_10_fu_1154_p2 <= std_logic_vector(unsigned(mul_ln36_19_reg_1890) + unsigned(mul_ln36_18_reg_1885));
    add_ln36_11_fu_1158_p2 <= std_logic_vector(unsigned(mul_ln36_17_reg_1880) + unsigned(mul_ln36_16_reg_1875));
    add_ln36_12_fu_1162_p2 <= std_logic_vector(unsigned(add_ln36_11_fu_1158_p2) + unsigned(add_ln36_10_fu_1154_p2));
    add_ln36_13_fu_1248_p2 <= std_logic_vector(unsigned(add_ln36_12_reg_1965) + unsigned(add_ln36_9_fu_1242_p2));
    add_ln36_14_fu_1262_p2 <= std_logic_vector(unsigned(add_ln36_13_reg_1990) + unsigned(add_ln36_6_reg_1985));
    add_ln36_15_fu_1168_p2 <= std_logic_vector(unsigned(mul_ln36_15_reg_1870) + unsigned(mul_ln36_14_reg_1865));
    add_ln36_16_fu_1172_p2 <= std_logic_vector(unsigned(mul_ln36_13_reg_1860) + unsigned(mul_ln36_12_reg_1855));
    add_ln36_17_fu_1176_p2 <= std_logic_vector(unsigned(add_ln36_16_fu_1172_p2) + unsigned(add_ln36_15_fu_1168_p2));
    add_ln36_18_fu_1182_p2 <= std_logic_vector(unsigned(mul_ln36_11_reg_1850) + unsigned(mul_ln36_10_reg_1845));
    add_ln36_19_fu_1186_p2 <= std_logic_vector(unsigned(mul_ln36_9_reg_1840) + unsigned(mul_ln36_8_reg_1835));
    add_ln36_1_fu_1219_p2 <= std_logic_vector(unsigned(mul_ln36_29_reg_1945) + unsigned(mul_ln36_28_reg_1940));
    add_ln36_20_fu_1190_p2 <= std_logic_vector(unsigned(add_ln36_19_fu_1186_p2) + unsigned(add_ln36_18_fu_1182_p2));
    add_ln36_21_fu_1253_p2 <= std_logic_vector(unsigned(add_ln36_20_reg_1975) + unsigned(add_ln36_17_reg_1970));
    add_ln36_22_fu_1196_p2 <= std_logic_vector(unsigned(mul_ln36_7_reg_1830) + unsigned(mul_ln36_6_reg_1825));
    add_ln36_23_fu_1200_p2 <= std_logic_vector(unsigned(mul_ln36_5_reg_1820) + unsigned(mul_ln36_4_reg_1815));
    add_ln36_24_fu_1204_p2 <= std_logic_vector(unsigned(add_ln36_23_fu_1200_p2) + unsigned(add_ln36_22_fu_1196_p2));
    add_ln36_25_fu_1126_p2 <= std_logic_vector(unsigned(mul_ln36_3_reg_1770) + unsigned(mul_ln36_2_reg_1765));
    add_ln36_26_fu_1130_p2 <= std_logic_vector(unsigned(mul_ln36_1_reg_1760) + unsigned(mul_ln36_reg_1755));
    add_ln36_27_fu_1134_p2 <= std_logic_vector(unsigned(add_ln36_26_fu_1130_p2) + unsigned(add_ln36_25_fu_1126_p2));
    add_ln36_28_fu_1210_p2 <= std_logic_vector(unsigned(add_ln36_27_reg_1915) + unsigned(add_ln36_24_fu_1204_p2));
    add_ln36_29_fu_1257_p2 <= std_logic_vector(unsigned(add_ln36_28_reg_1980) + unsigned(add_ln36_21_fu_1253_p2));
    add_ln36_2_fu_1223_p2 <= std_logic_vector(unsigned(add_ln36_1_fu_1219_p2) + unsigned(add_ln36_fu_1215_p2));
    add_ln36_3_fu_1140_p2 <= std_logic_vector(unsigned(mul_ln36_27_reg_1910) + unsigned(mul_ln36_26_reg_1905));
    add_ln36_4_fu_1144_p2 <= std_logic_vector(unsigned(mul_ln36_25_reg_1900) + unsigned(mul_ln36_24_reg_1895));
    add_ln36_5_fu_1148_p2 <= std_logic_vector(unsigned(add_ln36_4_fu_1144_p2) + unsigned(add_ln36_3_fu_1140_p2));
    add_ln36_6_fu_1229_p2 <= std_logic_vector(unsigned(add_ln36_5_reg_1960) + unsigned(add_ln36_2_fu_1223_p2));
    add_ln36_7_fu_1234_p2 <= std_logic_vector(unsigned(mul_ln36_23_reg_1935) + unsigned(mul_ln36_22_reg_1930));
    add_ln36_8_fu_1238_p2 <= std_logic_vector(unsigned(mul_ln36_21_reg_1925) + unsigned(mul_ln36_20_reg_1920));
    add_ln36_9_fu_1242_p2 <= std_logic_vector(unsigned(add_ln36_8_fu_1238_p2) + unsigned(add_ln36_7_fu_1234_p2));
    add_ln36_fu_1215_p2 <= std_logic_vector(unsigned(mul_ln36_31_reg_1955) + unsigned(mul_ln36_30_reg_1950));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter6, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter6, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter6, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter6, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln30_fu_1101_p2)
    begin
        if (((icmp_ln30_fu_1101_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_176, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv31_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_176;
        end if; 
    end process;


    grp_fu_801_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_801_ce <= ap_const_logic_1;
        else 
            grp_fu_801_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_801_p1 <= sext_ln36_31_cast_reg_1434(8 - 1 downto 0);

    grp_fu_806_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_806_ce <= ap_const_logic_1;
        else 
            grp_fu_806_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_806_p1 <= sext_ln36_30_cast_reg_1429(8 - 1 downto 0);

    grp_fu_811_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_811_ce <= ap_const_logic_1;
        else 
            grp_fu_811_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_811_p1 <= sext_ln36_29_cast_reg_1424(8 - 1 downto 0);

    grp_fu_816_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_816_ce <= ap_const_logic_1;
        else 
            grp_fu_816_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_816_p1 <= sext_ln36_28_cast_reg_1419(8 - 1 downto 0);

    grp_fu_821_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_821_ce <= ap_const_logic_1;
        else 
            grp_fu_821_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_821_p1 <= sext_ln36_27_cast_reg_1414(8 - 1 downto 0);

    grp_fu_826_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_826_ce <= ap_const_logic_1;
        else 
            grp_fu_826_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_826_p1 <= sext_ln36_26_cast_reg_1409(8 - 1 downto 0);

    grp_fu_831_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_831_ce <= ap_const_logic_1;
        else 
            grp_fu_831_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_831_p1 <= sext_ln36_25_cast_reg_1404(8 - 1 downto 0);

    grp_fu_836_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_836_ce <= ap_const_logic_1;
        else 
            grp_fu_836_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_836_p1 <= sext_ln36_24_cast_reg_1399(8 - 1 downto 0);

    grp_fu_841_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_841_ce <= ap_const_logic_1;
        else 
            grp_fu_841_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_841_p1 <= sext_ln36_23_cast_reg_1394(8 - 1 downto 0);

    grp_fu_846_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_846_ce <= ap_const_logic_1;
        else 
            grp_fu_846_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_846_p1 <= sext_ln36_22_cast_reg_1389(8 - 1 downto 0);

    grp_fu_851_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_851_ce <= ap_const_logic_1;
        else 
            grp_fu_851_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_851_p1 <= sext_ln36_21_cast_reg_1384(8 - 1 downto 0);

    grp_fu_856_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_856_ce <= ap_const_logic_1;
        else 
            grp_fu_856_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_856_p1 <= sext_ln36_20_cast_reg_1379(8 - 1 downto 0);

    grp_fu_861_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_861_ce <= ap_const_logic_1;
        else 
            grp_fu_861_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_861_p1 <= sext_ln36_19_cast_reg_1374(8 - 1 downto 0);

    grp_fu_866_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_866_ce <= ap_const_logic_1;
        else 
            grp_fu_866_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_866_p1 <= sext_ln36_18_cast_reg_1369(8 - 1 downto 0);

    grp_fu_871_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_871_ce <= ap_const_logic_1;
        else 
            grp_fu_871_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_871_p1 <= sext_ln36_17_cast_reg_1364(8 - 1 downto 0);

    grp_fu_876_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_876_ce <= ap_const_logic_1;
        else 
            grp_fu_876_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_876_p1 <= sext_ln36_16_cast_reg_1359(8 - 1 downto 0);

    grp_fu_881_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_881_ce <= ap_const_logic_1;
        else 
            grp_fu_881_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_881_p1 <= sext_ln36_15_cast_reg_1354(8 - 1 downto 0);

    grp_fu_886_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_886_ce <= ap_const_logic_1;
        else 
            grp_fu_886_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_886_p1 <= sext_ln36_14_cast_reg_1349(8 - 1 downto 0);

    grp_fu_891_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_891_ce <= ap_const_logic_1;
        else 
            grp_fu_891_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_891_p1 <= sext_ln36_13_cast_reg_1344(8 - 1 downto 0);

    grp_fu_896_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_896_ce <= ap_const_logic_1;
        else 
            grp_fu_896_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_896_p1 <= sext_ln36_12_cast_reg_1339(8 - 1 downto 0);

    grp_fu_901_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_901_ce <= ap_const_logic_1;
        else 
            grp_fu_901_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_901_p1 <= sext_ln36_7_cast_reg_1314(8 - 1 downto 0);

    grp_fu_906_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_906_ce <= ap_const_logic_1;
        else 
            grp_fu_906_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_906_p1 <= sext_ln36_6_cast_reg_1309(8 - 1 downto 0);

    grp_fu_911_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_911_ce <= ap_const_logic_1;
        else 
            grp_fu_911_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_911_p1 <= sext_ln36_5_cast_reg_1304(8 - 1 downto 0);

    grp_fu_916_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_916_ce <= ap_const_logic_1;
        else 
            grp_fu_916_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_916_p1 <= sext_ln36_4_cast_reg_1299(8 - 1 downto 0);

    grp_fu_921_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_921_ce <= ap_const_logic_1;
        else 
            grp_fu_921_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_921_p1 <= sext_ln36_11_cast_reg_1334(8 - 1 downto 0);

    grp_fu_926_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_926_ce <= ap_const_logic_1;
        else 
            grp_fu_926_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_926_p1 <= sext_ln36_10_cast_reg_1329(8 - 1 downto 0);

    grp_fu_931_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_931_ce <= ap_const_logic_1;
        else 
            grp_fu_931_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_931_p1 <= sext_ln36_9_cast_reg_1324(8 - 1 downto 0);

    grp_fu_936_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_936_ce <= ap_const_logic_1;
        else 
            grp_fu_936_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_936_p1 <= sext_ln36_8_cast_reg_1319(8 - 1 downto 0);

    grp_fu_941_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_941_ce <= ap_const_logic_1;
        else 
            grp_fu_941_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_941_p1 <= sext_ln36_3_cast_reg_1294(8 - 1 downto 0);

    grp_fu_946_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_946_ce <= ap_const_logic_1;
        else 
            grp_fu_946_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_946_p1 <= sext_ln36_2_cast_reg_1289(8 - 1 downto 0);

    grp_fu_951_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_951_ce <= ap_const_logic_1;
        else 
            grp_fu_951_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_951_p1 <= sext_ln36_cast_reg_1284(8 - 1 downto 0);

    grp_fu_956_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_956_ce <= ap_const_logic_1;
        else 
            grp_fu_956_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_956_p1 <= sext_ln36_1_cast_reg_1279(8 - 1 downto 0);
    icmp_ln30_fu_1101_p2 <= "1" when (signed(zext_ln30_1_fu_1097_p1) < signed(num_rows)) else "0";
    out_stream_TDATA <= std_logic_vector(unsigned(add_ln36_29_reg_1995) + unsigned(add_ln36_14_fu_1262_p2));

    out_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter6, out_stream_TREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_stream_TVALID_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            out_stream_TVALID <= ap_const_logic_1;
        else 
            out_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln36_10_cast_fu_1001_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_10),32));

        sext_ln36_11_cast_fu_1005_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_11),32));

        sext_ln36_12_cast_fu_1009_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_12),32));

        sext_ln36_13_cast_fu_1013_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_13),32));

        sext_ln36_14_cast_fu_1017_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_14),32));

        sext_ln36_15_cast_fu_1021_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_15),32));

        sext_ln36_16_cast_fu_1025_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_16),32));

        sext_ln36_17_cast_fu_1029_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_17),32));

        sext_ln36_18_cast_fu_1033_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_18),32));

        sext_ln36_19_cast_fu_1037_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_19),32));

        sext_ln36_1_cast_fu_961_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_1),32));

        sext_ln36_20_cast_fu_1041_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_20),32));

        sext_ln36_21_cast_fu_1045_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_21),32));

        sext_ln36_22_cast_fu_1049_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_22),32));

        sext_ln36_23_cast_fu_1053_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_23),32));

        sext_ln36_24_cast_fu_1057_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_24),32));

        sext_ln36_25_cast_fu_1061_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_25),32));

        sext_ln36_26_cast_fu_1065_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_26),32));

        sext_ln36_27_cast_fu_1069_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_27),32));

        sext_ln36_28_cast_fu_1073_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_28),32));

        sext_ln36_29_cast_fu_1077_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_29),32));

        sext_ln36_2_cast_fu_969_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_2),32));

        sext_ln36_30_cast_fu_1081_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_30),32));

        sext_ln36_31_cast_fu_1085_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_31),32));

        sext_ln36_3_cast_fu_973_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_3),32));

        sext_ln36_4_cast_fu_977_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_4),32));

        sext_ln36_5_cast_fu_981_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_5),32));

        sext_ln36_6_cast_fu_985_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_6),32));

        sext_ln36_7_cast_fu_989_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_7),32));

        sext_ln36_8_cast_fu_993_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_8),32));

        sext_ln36_9_cast_fu_997_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36_9),32));

        sext_ln36_cast_fu_965_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln36),32));

    weights_0_address0 <= zext_ln30_reg_1443_pp0_iter1_reg(5 - 1 downto 0);
    weights_0_ce0 <= weights_0_ce0_local;

    weights_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            weights_0_ce0_local <= ap_const_logic_1;
        else 
            weights_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_10_address0 <= zext_ln30_reg_1443_pp0_iter1_reg(5 - 1 downto 0);
    weights_10_ce0 <= weights_10_ce0_local;

    weights_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            weights_10_ce0_local <= ap_const_logic_1;
        else 
            weights_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_11_address0 <= zext_ln30_reg_1443_pp0_iter1_reg(5 - 1 downto 0);
    weights_11_ce0 <= weights_11_ce0_local;

    weights_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            weights_11_ce0_local <= ap_const_logic_1;
        else 
            weights_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_12_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_12_ce0 <= weights_12_ce0_local;

    weights_12_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_12_ce0_local <= ap_const_logic_1;
        else 
            weights_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_13_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_13_ce0 <= weights_13_ce0_local;

    weights_13_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_13_ce0_local <= ap_const_logic_1;
        else 
            weights_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_14_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_14_ce0 <= weights_14_ce0_local;

    weights_14_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_14_ce0_local <= ap_const_logic_1;
        else 
            weights_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_15_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_15_ce0 <= weights_15_ce0_local;

    weights_15_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_15_ce0_local <= ap_const_logic_1;
        else 
            weights_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_16_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_16_ce0 <= weights_16_ce0_local;

    weights_16_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_16_ce0_local <= ap_const_logic_1;
        else 
            weights_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_17_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_17_ce0 <= weights_17_ce0_local;

    weights_17_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_17_ce0_local <= ap_const_logic_1;
        else 
            weights_17_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_18_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_18_ce0 <= weights_18_ce0_local;

    weights_18_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_18_ce0_local <= ap_const_logic_1;
        else 
            weights_18_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_19_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_19_ce0 <= weights_19_ce0_local;

    weights_19_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_19_ce0_local <= ap_const_logic_1;
        else 
            weights_19_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_1_address0 <= zext_ln30_reg_1443_pp0_iter1_reg(5 - 1 downto 0);
    weights_1_ce0 <= weights_1_ce0_local;

    weights_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            weights_1_ce0_local <= ap_const_logic_1;
        else 
            weights_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_20_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_20_ce0 <= weights_20_ce0_local;

    weights_20_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_20_ce0_local <= ap_const_logic_1;
        else 
            weights_20_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_21_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_21_ce0 <= weights_21_ce0_local;

    weights_21_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_21_ce0_local <= ap_const_logic_1;
        else 
            weights_21_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_22_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_22_ce0 <= weights_22_ce0_local;

    weights_22_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_22_ce0_local <= ap_const_logic_1;
        else 
            weights_22_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_23_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_23_ce0 <= weights_23_ce0_local;

    weights_23_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_23_ce0_local <= ap_const_logic_1;
        else 
            weights_23_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_24_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_24_ce0 <= weights_24_ce0_local;

    weights_24_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_24_ce0_local <= ap_const_logic_1;
        else 
            weights_24_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_25_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_25_ce0 <= weights_25_ce0_local;

    weights_25_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_25_ce0_local <= ap_const_logic_1;
        else 
            weights_25_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_26_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_26_ce0 <= weights_26_ce0_local;

    weights_26_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_26_ce0_local <= ap_const_logic_1;
        else 
            weights_26_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_27_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_27_ce0 <= weights_27_ce0_local;

    weights_27_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_27_ce0_local <= ap_const_logic_1;
        else 
            weights_27_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_28_address0 <= zext_ln30_fu_1113_p1(5 - 1 downto 0);
    weights_28_ce0 <= weights_28_ce0_local;

    weights_28_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_28_ce0_local <= ap_const_logic_1;
        else 
            weights_28_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_29_address0 <= zext_ln30_fu_1113_p1(5 - 1 downto 0);
    weights_29_ce0 <= weights_29_ce0_local;

    weights_29_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_29_ce0_local <= ap_const_logic_1;
        else 
            weights_29_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_2_address0 <= zext_ln30_reg_1443_pp0_iter1_reg(5 - 1 downto 0);
    weights_2_ce0 <= weights_2_ce0_local;

    weights_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            weights_2_ce0_local <= ap_const_logic_1;
        else 
            weights_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_30_address0 <= zext_ln30_fu_1113_p1(5 - 1 downto 0);
    weights_30_ce0 <= weights_30_ce0_local;

    weights_30_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_30_ce0_local <= ap_const_logic_1;
        else 
            weights_30_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_31_address0 <= zext_ln30_fu_1113_p1(5 - 1 downto 0);
    weights_31_ce0 <= weights_31_ce0_local;

    weights_31_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_31_ce0_local <= ap_const_logic_1;
        else 
            weights_31_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_3_address0 <= zext_ln30_reg_1443_pp0_iter1_reg(5 - 1 downto 0);
    weights_3_ce0 <= weights_3_ce0_local;

    weights_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            weights_3_ce0_local <= ap_const_logic_1;
        else 
            weights_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_4_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_4_ce0 <= weights_4_ce0_local;

    weights_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_4_ce0_local <= ap_const_logic_1;
        else 
            weights_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_5_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_5_ce0 <= weights_5_ce0_local;

    weights_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_5_ce0_local <= ap_const_logic_1;
        else 
            weights_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_6_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_6_ce0 <= weights_6_ce0_local;

    weights_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_6_ce0_local <= ap_const_logic_1;
        else 
            weights_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_7_address0 <= zext_ln30_reg_1443(5 - 1 downto 0);
    weights_7_ce0 <= weights_7_ce0_local;

    weights_7_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weights_7_ce0_local <= ap_const_logic_1;
        else 
            weights_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_8_address0 <= zext_ln30_reg_1443_pp0_iter1_reg(5 - 1 downto 0);
    weights_8_ce0 <= weights_8_ce0_local;

    weights_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            weights_8_ce0_local <= ap_const_logic_1;
        else 
            weights_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weights_9_address0 <= zext_ln30_reg_1443_pp0_iter1_reg(5 - 1 downto 0);
    weights_9_ce0 <= weights_9_ce0_local;

    weights_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            weights_9_ce0_local <= ap_const_logic_1;
        else 
            weights_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln30_1_fu_1097_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),32));
    zext_ln30_fu_1113_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),64));
end behav;
