-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_25_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    p_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    p_out1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out1_ap_vld : OUT STD_LOGIC;
    p_out2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out2_ap_vld : OUT STD_LOGIC;
    p_out3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out3_ap_vld : OUT STD_LOGIC;
    p_out4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out4_ap_vld : OUT STD_LOGIC;
    p_out5 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out5_ap_vld : OUT STD_LOGIC;
    p_out6 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out6_ap_vld : OUT STD_LOGIC;
    p_out7 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out7_ap_vld : OUT STD_LOGIC;
    p_out8 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out8_ap_vld : OUT STD_LOGIC;
    p_out9 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out9_ap_vld : OUT STD_LOGIC;
    p_out10 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out10_ap_vld : OUT STD_LOGIC;
    p_out11 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out11_ap_vld : OUT STD_LOGIC;
    p_out12 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out12_ap_vld : OUT STD_LOGIC;
    p_out13 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out13_ap_vld : OUT STD_LOGIC;
    p_out14 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out14_ap_vld : OUT STD_LOGIC;
    p_out15 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out15_ap_vld : OUT STD_LOGIC;
    p_out16 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out16_ap_vld : OUT STD_LOGIC;
    p_out17 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out17_ap_vld : OUT STD_LOGIC;
    p_out18 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out18_ap_vld : OUT STD_LOGIC;
    p_out19 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out19_ap_vld : OUT STD_LOGIC;
    p_out20 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out20_ap_vld : OUT STD_LOGIC;
    p_out21 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out21_ap_vld : OUT STD_LOGIC;
    p_out22 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out22_ap_vld : OUT STD_LOGIC;
    p_out23 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out23_ap_vld : OUT STD_LOGIC;
    p_out24 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out24_ap_vld : OUT STD_LOGIC;
    p_out25 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out25_ap_vld : OUT STD_LOGIC;
    p_out26 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out26_ap_vld : OUT STD_LOGIC;
    p_out27 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out27_ap_vld : OUT STD_LOGIC;
    p_out28 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out28_ap_vld : OUT STD_LOGIC;
    p_out29 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out29_ap_vld : OUT STD_LOGIC;
    p_out30 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out30_ap_vld : OUT STD_LOGIC;
    p_out31 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out31_ap_vld : OUT STD_LOGIC );
end;


architecture behav of dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_25_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln25_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal trunc_ln25_fu_544_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln25_reg_1109 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_162 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln25_fu_538_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal empty_fu_166 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal empty_45_fu_170 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_46_fu_174 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_47_fu_178 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_48_fu_182 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_49_fu_186 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_50_fu_190 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_51_fu_194 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_52_fu_198 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_53_fu_202 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_54_fu_206 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_55_fu_210 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_56_fu_214 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_57_fu_218 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_58_fu_222 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_59_fu_226 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_60_fu_230 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_61_fu_234 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_62_fu_238 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_63_fu_242 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_64_fu_246 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_65_fu_250 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_66_fu_254 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_67_fu_258 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_68_fu_262 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_69_fu_266 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_70_fu_270 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_71_fu_274 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_72_fu_278 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_73_fu_282 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_74_fu_286 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_75_fu_290 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dense_gemv_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component dense_gemv_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln25_fu_532_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_162 <= add_ln25_fu_538_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_162 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_1))) then
                empty_45_fu_170 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_2))) then
                empty_46_fu_174 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_3))) then
                empty_47_fu_178 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_4))) then
                empty_48_fu_182 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_5))) then
                empty_49_fu_186 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_6))) then
                empty_50_fu_190 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_7))) then
                empty_51_fu_194 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_8))) then
                empty_52_fu_198 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_9))) then
                empty_53_fu_202 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_A))) then
                empty_54_fu_206 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_B))) then
                empty_55_fu_210 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_C))) then
                empty_56_fu_214 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_D))) then
                empty_57_fu_218 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_E))) then
                empty_58_fu_222 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_F))) then
                empty_59_fu_226 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_10))) then
                empty_60_fu_230 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_11))) then
                empty_61_fu_234 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_12))) then
                empty_62_fu_238 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_13))) then
                empty_63_fu_242 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_14))) then
                empty_64_fu_246 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_15))) then
                empty_65_fu_250 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_16))) then
                empty_66_fu_254 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_17))) then
                empty_67_fu_258 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_18))) then
                empty_68_fu_262 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_19))) then
                empty_69_fu_266 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_1A))) then
                empty_70_fu_270 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_1B))) then
                empty_71_fu_274 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_1C))) then
                empty_72_fu_278 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_1D))) then
                empty_73_fu_282 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_1E))) then
                empty_74_fu_286 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_1F))) then
                empty_75_fu_290 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln25_reg_1109 = ap_const_lv5_0))) then
                empty_fu_166 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln25_reg_1109 <= trunc_ln25_fu_544_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln25_fu_538_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, in_stream_TVALID)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, in_stream_TVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, in_stream_TVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, in_stream_TVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln25_fu_532_p2)
    begin
        if (((icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_162, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_162;
        end if; 
    end process;

    icmp_ln25_fu_532_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv6_20) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, in_stream_TVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    p_out <= empty_75_fu_290;
    p_out1 <= empty_74_fu_286;
    p_out10 <= empty_65_fu_250;

    p_out10_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out10_ap_vld <= ap_const_logic_1;
        else 
            p_out10_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out11 <= empty_64_fu_246;

    p_out11_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out11_ap_vld <= ap_const_logic_1;
        else 
            p_out11_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out12 <= empty_63_fu_242;

    p_out12_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out12_ap_vld <= ap_const_logic_1;
        else 
            p_out12_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out13 <= empty_62_fu_238;

    p_out13_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out13_ap_vld <= ap_const_logic_1;
        else 
            p_out13_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out14 <= empty_61_fu_234;

    p_out14_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out14_ap_vld <= ap_const_logic_1;
        else 
            p_out14_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out15 <= empty_60_fu_230;

    p_out15_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out15_ap_vld <= ap_const_logic_1;
        else 
            p_out15_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out16 <= empty_59_fu_226;

    p_out16_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out16_ap_vld <= ap_const_logic_1;
        else 
            p_out16_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out17 <= empty_58_fu_222;

    p_out17_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out17_ap_vld <= ap_const_logic_1;
        else 
            p_out17_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out18 <= empty_57_fu_218;

    p_out18_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out18_ap_vld <= ap_const_logic_1;
        else 
            p_out18_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out19 <= empty_56_fu_214;

    p_out19_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out19_ap_vld <= ap_const_logic_1;
        else 
            p_out19_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out1_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out1_ap_vld <= ap_const_logic_1;
        else 
            p_out1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out2 <= empty_73_fu_282;
    p_out20 <= empty_55_fu_210;

    p_out20_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out20_ap_vld <= ap_const_logic_1;
        else 
            p_out20_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out21 <= empty_54_fu_206;

    p_out21_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out21_ap_vld <= ap_const_logic_1;
        else 
            p_out21_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out22 <= empty_53_fu_202;

    p_out22_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out22_ap_vld <= ap_const_logic_1;
        else 
            p_out22_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out23 <= empty_52_fu_198;

    p_out23_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out23_ap_vld <= ap_const_logic_1;
        else 
            p_out23_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out24 <= empty_51_fu_194;

    p_out24_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out24_ap_vld <= ap_const_logic_1;
        else 
            p_out24_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out25 <= empty_50_fu_190;

    p_out25_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out25_ap_vld <= ap_const_logic_1;
        else 
            p_out25_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out26 <= empty_49_fu_186;

    p_out26_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out26_ap_vld <= ap_const_logic_1;
        else 
            p_out26_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out27 <= empty_48_fu_182;

    p_out27_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out27_ap_vld <= ap_const_logic_1;
        else 
            p_out27_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out28 <= empty_47_fu_178;

    p_out28_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out28_ap_vld <= ap_const_logic_1;
        else 
            p_out28_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out29 <= empty_46_fu_174;

    p_out29_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out29_ap_vld <= ap_const_logic_1;
        else 
            p_out29_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out2_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out2_ap_vld <= ap_const_logic_1;
        else 
            p_out2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out3 <= empty_72_fu_278;
    p_out30 <= empty_45_fu_170;

    p_out30_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out30_ap_vld <= ap_const_logic_1;
        else 
            p_out30_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out31 <= empty_fu_166;

    p_out31_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out31_ap_vld <= ap_const_logic_1;
        else 
            p_out31_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out3_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out3_ap_vld <= ap_const_logic_1;
        else 
            p_out3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out4 <= empty_71_fu_274;

    p_out4_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out4_ap_vld <= ap_const_logic_1;
        else 
            p_out4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out5 <= empty_70_fu_270;

    p_out5_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out5_ap_vld <= ap_const_logic_1;
        else 
            p_out5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out6 <= empty_69_fu_266;

    p_out6_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out6_ap_vld <= ap_const_logic_1;
        else 
            p_out6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out7 <= empty_68_fu_262;

    p_out7_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out7_ap_vld <= ap_const_logic_1;
        else 
            p_out7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out8 <= empty_67_fu_258;

    p_out8_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out8_ap_vld <= ap_const_logic_1;
        else 
            p_out8_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out9 <= empty_66_fu_254;

    p_out9_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out9_ap_vld <= ap_const_logic_1;
        else 
            p_out9_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln25_fu_532_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln25_fu_532_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln25_fu_544_p1 <= ap_sig_allocacmp_i_2(5 - 1 downto 0);
end behav;
