-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_gemv is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 13;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of dense_gemv is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dense_gemv_dense_gemv,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a12t-cpg238-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.207000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=64,HLS_SYN_DSP=0,HLS_SYN_FF=10698,HLS_SYN_LUT=5265,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal weights_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_7_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_8_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_9_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_10_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_11_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_12_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_13_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_14_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_15_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_16_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_17_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_18_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_19_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_20_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_21_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_22_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_23_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_24_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_25_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_26_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_27_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_28_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_29_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_30_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_31_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal num_rows : STD_LOGIC_VECTOR (31 downto 0);
    signal num_rows_read_reg_776 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_done : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_idle : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_ready : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_in_stream_TREADY : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out1_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out2_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out3_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out4_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out5 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out5_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out6 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out6_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out7 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out7_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out8 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out8_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out9 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out9_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out10 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out10_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out11 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out11_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out12 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out12_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out13 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out13_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out14 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out14_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out15 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out15_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out16 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out16_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out17 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out17_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out18 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out18_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out19 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out19_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out20 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out20_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out21 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out21_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out22 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out22_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out23 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out23_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out24 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out24_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out25 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out25_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out26 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out26_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out27 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out27_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out28 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out28_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out29 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out29_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out30 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out30_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out31 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out31_ap_vld : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_done : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_idle : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_ready : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TREADY : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_ce0 : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TVALID : STD_LOGIC;
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal out_stream_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal regslice_both_out_stream_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal regslice_both_in_stream_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_25_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        p_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC;
        p_out6 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out6_ap_vld : OUT STD_LOGIC;
        p_out7 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out7_ap_vld : OUT STD_LOGIC;
        p_out8 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out8_ap_vld : OUT STD_LOGIC;
        p_out9 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out9_ap_vld : OUT STD_LOGIC;
        p_out10 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out10_ap_vld : OUT STD_LOGIC;
        p_out11 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out11_ap_vld : OUT STD_LOGIC;
        p_out12 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out12_ap_vld : OUT STD_LOGIC;
        p_out13 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out13_ap_vld : OUT STD_LOGIC;
        p_out14 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out14_ap_vld : OUT STD_LOGIC;
        p_out15 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out15_ap_vld : OUT STD_LOGIC;
        p_out16 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out16_ap_vld : OUT STD_LOGIC;
        p_out17 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out17_ap_vld : OUT STD_LOGIC;
        p_out18 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out18_ap_vld : OUT STD_LOGIC;
        p_out19 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out19_ap_vld : OUT STD_LOGIC;
        p_out20 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out20_ap_vld : OUT STD_LOGIC;
        p_out21 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out21_ap_vld : OUT STD_LOGIC;
        p_out22 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out22_ap_vld : OUT STD_LOGIC;
        p_out23 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out23_ap_vld : OUT STD_LOGIC;
        p_out24 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out24_ap_vld : OUT STD_LOGIC;
        p_out25 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out25_ap_vld : OUT STD_LOGIC;
        p_out26 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out26_ap_vld : OUT STD_LOGIC;
        p_out27 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out27_ap_vld : OUT STD_LOGIC;
        p_out28 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out28_ap_vld : OUT STD_LOGIC;
        p_out29 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out29_ap_vld : OUT STD_LOGIC;
        p_out30 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out30_ap_vld : OUT STD_LOGIC;
        p_out31 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out31_ap_vld : OUT STD_LOGIC );
    end component;


    component dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_30_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        num_rows : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_0_ce0 : OUT STD_LOGIC;
        weights_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_1_ce0 : OUT STD_LOGIC;
        weights_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_2_ce0 : OUT STD_LOGIC;
        weights_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_3_ce0 : OUT STD_LOGIC;
        weights_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_4_ce0 : OUT STD_LOGIC;
        weights_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_5_ce0 : OUT STD_LOGIC;
        weights_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_6_ce0 : OUT STD_LOGIC;
        weights_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_7_ce0 : OUT STD_LOGIC;
        weights_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_8_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_8_ce0 : OUT STD_LOGIC;
        weights_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_9_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_9_ce0 : OUT STD_LOGIC;
        weights_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_10_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_10_ce0 : OUT STD_LOGIC;
        weights_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_11_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_11_ce0 : OUT STD_LOGIC;
        weights_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_12_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_12_ce0 : OUT STD_LOGIC;
        weights_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_13_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_13_ce0 : OUT STD_LOGIC;
        weights_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_14_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_14_ce0 : OUT STD_LOGIC;
        weights_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_15_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_15_ce0 : OUT STD_LOGIC;
        weights_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_16_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_16_ce0 : OUT STD_LOGIC;
        weights_16_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_17_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_17_ce0 : OUT STD_LOGIC;
        weights_17_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_18_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_18_ce0 : OUT STD_LOGIC;
        weights_18_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_19_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_19_ce0 : OUT STD_LOGIC;
        weights_19_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_20_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_20_ce0 : OUT STD_LOGIC;
        weights_20_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_21_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_21_ce0 : OUT STD_LOGIC;
        weights_21_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_22_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_22_ce0 : OUT STD_LOGIC;
        weights_22_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_23_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_23_ce0 : OUT STD_LOGIC;
        weights_23_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_24_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_24_ce0 : OUT STD_LOGIC;
        weights_24_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_25_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_25_ce0 : OUT STD_LOGIC;
        weights_25_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_26_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_26_ce0 : OUT STD_LOGIC;
        weights_26_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_27_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_27_ce0 : OUT STD_LOGIC;
        weights_27_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_28_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_28_ce0 : OUT STD_LOGIC;
        weights_28_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_29_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_29_ce0 : OUT STD_LOGIC;
        weights_29_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_30_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_30_ce0 : OUT STD_LOGIC;
        weights_30_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_31_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        weights_31_ce0 : OUT STD_LOGIC;
        weights_31_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln36_31 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_30 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_29 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_28 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_27 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_26 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_25 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_24 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_23 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_22 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_21 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_20 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_19 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_18 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_17 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_16 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_15 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_14 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_13 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_12 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_11 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_10 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_9 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_8 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_7 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_6 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_5 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln36_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC );
    end component;


    component dense_gemv_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        num_rows : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_0_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_0_ce0 : IN STD_LOGIC;
        weights_0_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_1_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_1_ce0 : IN STD_LOGIC;
        weights_1_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_2_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_2_ce0 : IN STD_LOGIC;
        weights_2_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_3_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_3_ce0 : IN STD_LOGIC;
        weights_3_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_4_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_4_ce0 : IN STD_LOGIC;
        weights_4_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_5_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_5_ce0 : IN STD_LOGIC;
        weights_5_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_6_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_6_ce0 : IN STD_LOGIC;
        weights_6_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_7_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_7_ce0 : IN STD_LOGIC;
        weights_7_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_8_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_8_ce0 : IN STD_LOGIC;
        weights_8_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_9_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_9_ce0 : IN STD_LOGIC;
        weights_9_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_10_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_10_ce0 : IN STD_LOGIC;
        weights_10_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_11_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_11_ce0 : IN STD_LOGIC;
        weights_11_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_12_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_12_ce0 : IN STD_LOGIC;
        weights_12_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_13_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_13_ce0 : IN STD_LOGIC;
        weights_13_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_14_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_14_ce0 : IN STD_LOGIC;
        weights_14_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_15_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_15_ce0 : IN STD_LOGIC;
        weights_15_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_16_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_16_ce0 : IN STD_LOGIC;
        weights_16_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_17_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_17_ce0 : IN STD_LOGIC;
        weights_17_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_18_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_18_ce0 : IN STD_LOGIC;
        weights_18_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_19_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_19_ce0 : IN STD_LOGIC;
        weights_19_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_20_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_20_ce0 : IN STD_LOGIC;
        weights_20_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_21_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_21_ce0 : IN STD_LOGIC;
        weights_21_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_22_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_22_ce0 : IN STD_LOGIC;
        weights_22_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_23_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_23_ce0 : IN STD_LOGIC;
        weights_23_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_24_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_24_ce0 : IN STD_LOGIC;
        weights_24_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_25_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_25_ce0 : IN STD_LOGIC;
        weights_25_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_26_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_26_ce0 : IN STD_LOGIC;
        weights_26_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_27_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_27_ce0 : IN STD_LOGIC;
        weights_27_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_28_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_28_ce0 : IN STD_LOGIC;
        weights_28_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_29_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_29_ce0 : IN STD_LOGIC;
        weights_29_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_30_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_30_ce0 : IN STD_LOGIC;
        weights_30_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        weights_31_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        weights_31_ce0 : IN STD_LOGIC;
        weights_31_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component dense_gemv_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314 : component dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_25_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start,
        ap_done => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_done,
        ap_idle => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_idle,
        ap_ready => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_in_stream_TREADY,
        p_out => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out,
        p_out_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out_ap_vld,
        p_out1 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out1,
        p_out1_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out1_ap_vld,
        p_out2 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out2,
        p_out2_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out2_ap_vld,
        p_out3 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out3,
        p_out3_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out3_ap_vld,
        p_out4 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out4,
        p_out4_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out4_ap_vld,
        p_out5 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out5,
        p_out5_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out5_ap_vld,
        p_out6 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out6,
        p_out6_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out6_ap_vld,
        p_out7 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out7,
        p_out7_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out7_ap_vld,
        p_out8 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out8,
        p_out8_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out8_ap_vld,
        p_out9 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out9,
        p_out9_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out9_ap_vld,
        p_out10 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out10,
        p_out10_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out10_ap_vld,
        p_out11 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out11,
        p_out11_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out11_ap_vld,
        p_out12 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out12,
        p_out12_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out12_ap_vld,
        p_out13 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out13,
        p_out13_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out13_ap_vld,
        p_out14 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out14,
        p_out14_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out14_ap_vld,
        p_out15 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out15,
        p_out15_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out15_ap_vld,
        p_out16 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out16,
        p_out16_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out16_ap_vld,
        p_out17 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out17,
        p_out17_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out17_ap_vld,
        p_out18 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out18,
        p_out18_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out18_ap_vld,
        p_out19 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out19,
        p_out19_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out19_ap_vld,
        p_out20 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out20,
        p_out20_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out20_ap_vld,
        p_out21 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out21,
        p_out21_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out21_ap_vld,
        p_out22 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out22,
        p_out22_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out22_ap_vld,
        p_out23 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out23,
        p_out23_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out23_ap_vld,
        p_out24 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out24,
        p_out24_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out24_ap_vld,
        p_out25 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out25,
        p_out25_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out25_ap_vld,
        p_out26 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out26,
        p_out26_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out26_ap_vld,
        p_out27 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out27,
        p_out27_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out27_ap_vld,
        p_out28 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out28,
        p_out28_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out28_ap_vld,
        p_out29 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out29,
        p_out29_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out29_ap_vld,
        p_out30 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out30,
        p_out30_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out30_ap_vld,
        p_out31 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out31,
        p_out31_ap_vld => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out31_ap_vld);

    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352 : component dense_gemv_dense_gemv_Pipeline_VITIS_LOOP_30_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start,
        ap_done => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_done,
        ap_idle => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_idle,
        ap_ready => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_ready,
        out_stream_TREADY => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TREADY,
        num_rows => num_rows_read_reg_776,
        weights_0_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_address0,
        weights_0_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_ce0,
        weights_0_q0 => weights_0_q0,
        weights_1_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_address0,
        weights_1_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_ce0,
        weights_1_q0 => weights_1_q0,
        weights_2_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_address0,
        weights_2_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_ce0,
        weights_2_q0 => weights_2_q0,
        weights_3_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_address0,
        weights_3_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_ce0,
        weights_3_q0 => weights_3_q0,
        weights_4_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_address0,
        weights_4_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_ce0,
        weights_4_q0 => weights_4_q0,
        weights_5_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_address0,
        weights_5_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_ce0,
        weights_5_q0 => weights_5_q0,
        weights_6_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_address0,
        weights_6_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_ce0,
        weights_6_q0 => weights_6_q0,
        weights_7_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_address0,
        weights_7_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_ce0,
        weights_7_q0 => weights_7_q0,
        weights_8_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_address0,
        weights_8_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_ce0,
        weights_8_q0 => weights_8_q0,
        weights_9_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_address0,
        weights_9_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_ce0,
        weights_9_q0 => weights_9_q0,
        weights_10_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_address0,
        weights_10_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_ce0,
        weights_10_q0 => weights_10_q0,
        weights_11_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_address0,
        weights_11_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_ce0,
        weights_11_q0 => weights_11_q0,
        weights_12_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_address0,
        weights_12_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_ce0,
        weights_12_q0 => weights_12_q0,
        weights_13_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_address0,
        weights_13_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_ce0,
        weights_13_q0 => weights_13_q0,
        weights_14_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_address0,
        weights_14_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_ce0,
        weights_14_q0 => weights_14_q0,
        weights_15_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_address0,
        weights_15_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_ce0,
        weights_15_q0 => weights_15_q0,
        weights_16_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_address0,
        weights_16_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_ce0,
        weights_16_q0 => weights_16_q0,
        weights_17_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_address0,
        weights_17_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_ce0,
        weights_17_q0 => weights_17_q0,
        weights_18_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_address0,
        weights_18_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_ce0,
        weights_18_q0 => weights_18_q0,
        weights_19_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_address0,
        weights_19_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_ce0,
        weights_19_q0 => weights_19_q0,
        weights_20_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_address0,
        weights_20_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_ce0,
        weights_20_q0 => weights_20_q0,
        weights_21_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_address0,
        weights_21_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_ce0,
        weights_21_q0 => weights_21_q0,
        weights_22_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_address0,
        weights_22_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_ce0,
        weights_22_q0 => weights_22_q0,
        weights_23_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_address0,
        weights_23_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_ce0,
        weights_23_q0 => weights_23_q0,
        weights_24_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_address0,
        weights_24_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_ce0,
        weights_24_q0 => weights_24_q0,
        weights_25_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_address0,
        weights_25_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_ce0,
        weights_25_q0 => weights_25_q0,
        weights_26_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_address0,
        weights_26_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_ce0,
        weights_26_q0 => weights_26_q0,
        weights_27_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_address0,
        weights_27_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_ce0,
        weights_27_q0 => weights_27_q0,
        weights_28_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_address0,
        weights_28_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_ce0,
        weights_28_q0 => weights_28_q0,
        weights_29_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_address0,
        weights_29_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_ce0,
        weights_29_q0 => weights_29_q0,
        weights_30_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_address0,
        weights_30_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_ce0,
        weights_30_q0 => weights_30_q0,
        weights_31_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_address0,
        weights_31_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_ce0,
        weights_31_q0 => weights_31_q0,
        sext_ln36_31 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out,
        sext_ln36_30 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out1,
        sext_ln36_29 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out2,
        sext_ln36_28 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out3,
        sext_ln36_27 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out4,
        sext_ln36_26 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out5,
        sext_ln36_25 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out6,
        sext_ln36_24 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out7,
        sext_ln36_23 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out8,
        sext_ln36_22 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out9,
        sext_ln36_21 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out10,
        sext_ln36_20 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out11,
        sext_ln36_19 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out12,
        sext_ln36_18 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out13,
        sext_ln36_17 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out14,
        sext_ln36_16 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out15,
        sext_ln36_15 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out16,
        sext_ln36_14 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out17,
        sext_ln36_13 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out18,
        sext_ln36_12 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out19,
        sext_ln36_11 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out20,
        sext_ln36_10 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out21,
        sext_ln36_9 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out22,
        sext_ln36_8 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out23,
        sext_ln36_7 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out24,
        sext_ln36_6 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out25,
        sext_ln36_5 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out26,
        sext_ln36_4 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out27,
        sext_ln36_3 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out28,
        sext_ln36_2 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out29,
        sext_ln36 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out31,
        sext_ln36_1 => grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_p_out30,
        out_stream_TDATA => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TDATA,
        out_stream_TVALID => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TVALID);

    control_s_axi_U : component dense_gemv_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        num_rows => num_rows,
        weights_0_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_address0,
        weights_0_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_0_ce0,
        weights_0_q0 => weights_0_q0,
        weights_1_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_address0,
        weights_1_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_1_ce0,
        weights_1_q0 => weights_1_q0,
        weights_2_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_address0,
        weights_2_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_2_ce0,
        weights_2_q0 => weights_2_q0,
        weights_3_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_address0,
        weights_3_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_3_ce0,
        weights_3_q0 => weights_3_q0,
        weights_4_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_address0,
        weights_4_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_4_ce0,
        weights_4_q0 => weights_4_q0,
        weights_5_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_address0,
        weights_5_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_5_ce0,
        weights_5_q0 => weights_5_q0,
        weights_6_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_address0,
        weights_6_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_6_ce0,
        weights_6_q0 => weights_6_q0,
        weights_7_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_address0,
        weights_7_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_7_ce0,
        weights_7_q0 => weights_7_q0,
        weights_8_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_address0,
        weights_8_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_8_ce0,
        weights_8_q0 => weights_8_q0,
        weights_9_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_address0,
        weights_9_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_9_ce0,
        weights_9_q0 => weights_9_q0,
        weights_10_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_address0,
        weights_10_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_10_ce0,
        weights_10_q0 => weights_10_q0,
        weights_11_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_address0,
        weights_11_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_11_ce0,
        weights_11_q0 => weights_11_q0,
        weights_12_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_address0,
        weights_12_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_12_ce0,
        weights_12_q0 => weights_12_q0,
        weights_13_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_address0,
        weights_13_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_13_ce0,
        weights_13_q0 => weights_13_q0,
        weights_14_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_address0,
        weights_14_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_14_ce0,
        weights_14_q0 => weights_14_q0,
        weights_15_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_address0,
        weights_15_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_15_ce0,
        weights_15_q0 => weights_15_q0,
        weights_16_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_address0,
        weights_16_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_16_ce0,
        weights_16_q0 => weights_16_q0,
        weights_17_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_address0,
        weights_17_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_17_ce0,
        weights_17_q0 => weights_17_q0,
        weights_18_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_address0,
        weights_18_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_18_ce0,
        weights_18_q0 => weights_18_q0,
        weights_19_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_address0,
        weights_19_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_19_ce0,
        weights_19_q0 => weights_19_q0,
        weights_20_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_address0,
        weights_20_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_20_ce0,
        weights_20_q0 => weights_20_q0,
        weights_21_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_address0,
        weights_21_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_21_ce0,
        weights_21_q0 => weights_21_q0,
        weights_22_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_address0,
        weights_22_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_22_ce0,
        weights_22_q0 => weights_22_q0,
        weights_23_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_address0,
        weights_23_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_23_ce0,
        weights_23_q0 => weights_23_q0,
        weights_24_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_address0,
        weights_24_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_24_ce0,
        weights_24_q0 => weights_24_q0,
        weights_25_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_address0,
        weights_25_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_25_ce0,
        weights_25_q0 => weights_25_q0,
        weights_26_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_address0,
        weights_26_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_26_ce0,
        weights_26_q0 => weights_26_q0,
        weights_27_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_address0,
        weights_27_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_27_ce0,
        weights_27_q0 => weights_27_q0,
        weights_28_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_address0,
        weights_28_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_28_ce0,
        weights_28_q0 => weights_28_q0,
        weights_29_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_address0,
        weights_29_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_29_ce0,
        weights_29_q0 => weights_29_q0,
        weights_30_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_address0,
        weights_30_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_30_ce0,
        weights_30_q0 => weights_30_q0,
        weights_31_address0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_address0,
        weights_31_ce0 => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_weights_31_ce0,
        weights_31_q0 => weights_31_q0,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_in_stream_U : component dense_gemv_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_U_apdone_blk);

    regslice_both_out_stream_U : component dense_gemv_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_ready = ap_const_logic_1)) then 
                    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_ready = ap_const_logic_1)) then 
                    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                num_rows_read_reg_776 <= num_rows;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                out_stream_TDATA_reg <= grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_done, grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state6, regslice_both_out_stream_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((regslice_both_out_stream_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_done)
    begin
        if ((grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_done)
    begin
        if ((grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(regslice_both_out_stream_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state6, regslice_both_out_stream_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, regslice_both_out_stream_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start <= grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_ap_start_reg;
    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start <= grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_ap_start_reg;
    grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state5);
    in_stream_TREADY <= regslice_both_in_stream_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_in_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_stream_TREADY_int_regslice <= grp_dense_gemv_Pipeline_VITIS_LOOP_25_1_fu_314_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    out_stream_TDATA_int_regslice_assign_proc : process(grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TDATA, grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TVALID, ap_CS_fsm_state5, out_stream_TDATA_reg)
    begin
        if (((grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            out_stream_TDATA_int_regslice <= grp_dense_gemv_Pipeline_VITIS_LOOP_30_2_fu_352_out_stream_TDATA;
        else 
            out_stream_TDATA_int_regslice <= out_stream_TDATA_reg;
        end if; 
    end process;

    out_stream_TVALID <= regslice_both_out_stream_U_vld_out;
end behav;
